### ISSUE TITLE
Can't get past "searching for bluetooth and usb devices" screen

### ISSUE THREAD

**Issue by vladimirgluten** [FydeOS/chromium_os-raspberry_pi#101]
I'm on the screen, it finds my mouse and KB, but clicking on Continue does nothing.  it's registering that I click, because I can see the little animation.  The Shutdown button does work, however.  This is 83.0.4103.45 (Platform 13020.39.2020_7_12_1601 (test build - yang) developer-build rpi3)  Just downloaded it today.

**Comment by yunshansimon** [comment]
I have no idea what's you're talking about. Can you take a screenshot?

**Comment by vladimirgluten** [comment]
I took a pic with my phone, since I can't take a screenshot with ChromeOS, partly because I'm not loaded fully in and partly because I don't even know how to do a screenshot on ChromeOS (never actually used it before)
![IMG_4443](https://user-images.githubusercontent.com/27385251/100243737-d0d1a000-2efb-11eb-8b0c-84031372d97b.jpg)

When I click on the Continue button, nothing happens, it doesn't continue to load the OS

**Comment by yunshansimon** [comment]
We will release a new version with more features and more stability, please try the new one.
