### ISSUE TITLE
Wont boot

### ISSUE THREAD

**Issue by anaskatt01** [FydeOS/chromium_os-raspberry_pi#103]
My raspberry pi 3b+ won't boot with the is I have tried to reinstall the os but it didn't work yes I have USb boot enables and I've used it before so that's not the problem

**Comment by yunshansimon** [comment]
ChromiumOS for Rpi doesn't support boot from usb. I don't know how to boot from usb either. Maybe we can take a shot with the latest release. You can modify the `cmdline.txt` in partition 12.  Change `root=/dev/mmcblk0p3` to `root=/dev/sda3` . Tell me the result wether or not it works.

**Comment by anaskatt01** [comment]
> ChromiumOS for Rpi doesn't support boot from usb. I don't know how to boot from usb either. Maybe we can take a shot with the latest release. You can modify the `cmdline.txt` in partition 12. Change `root=/dev/mmcblk0p3` to `root=/dev/sda3` . Tell me the result wether or not it works. So thankyou for the response however i am no longer looking into this project because of some technical issues so please close this question
