### ISSUE TITLE
[Issue report] The partition size are fixed 2GB and didn't resize with the SD card.

### ISSUE THREAD

**Issue by lygstate** [FydeOS/chromium_os-raspberry_pi#104]
**Describe the bug or issue**

**Describe your setup**
 - Your Raspberry Pi model and spec variant, e.g. 4B with 2GB RAM
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS r77 r3
 - Your hardware configuration and setup, e.g. how you have wired the Pi board with any other peripheral connected to it

**To Reproduce**

**Expected behaviour**

**Screenshots and/or hardware setup photos**
If applicable, add screenshots to help explain your problem. If your problem is hardware related, it's much easier to include a photo of how your setup looks like.

**Additional context**

**Comment by yunshansimon** [comment]
There were a lots of bugs in old release. We have fixed the bug in latest release.
