### ISSUE TITLE
Would it be possible to chroot into FydeOS from Raspbian?

### ISSUE THREAD

**Issue by Botspot** [FydeOS/chromium_os-raspberry_pi#106]
The title says most of it.

I've developed and currently maintain [vdesktop](https://github.com/Botspot/vdesktop) - a virtual machine software to run RPi OS'es on Raspberry Pi.  
Chromium OS support would be very cool, even if it's CLI-only.

How would that work? I'm not familiar with how chromium OS works under the hood. Does that type of linux have a root filesystem somewhere, containing folders like /dev, /sys, /bin, and /usr?

**Comment by yunshansimon** [comment]
The chromium for ChromiumOS needs more kernel modules which don't include in RpiOS kernel. You need to combine two kernel config files, some of the flags conflict each other. I don't think it will work.

**Comment by Botspot** [comment]
@yunshansimon Would it be possible to access CrOS's linux subsystem? And not Chromium?

**Comment by yunshansimon** [comment]
We provide "crostini" in the next release. It's a virtual machine running Debian Linux.
