### ISSUE TITLE
I can't input Japanese on US keyboard

### ISSUE THREAD

**Issue by kenryuS** [FydeOS/chromium_os-raspberry_pi#115]
**Describe the bug or issue**
I can't input Japanese on a US keyboard. It just shows the alphabet 

**Describe your setup**
 - Your Raspberry Pi 4B with 4GB RAM
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS r86.0424.168 r4

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Languages and inputs'
3. Select Japanese on Languages column
4. Select 'Japanese input (for us keyboard)' on 'managing input column'
5. change the input method
6. Try to type 'あいうえお' by type 'a', 'i', 'u', 'e', and 'o' on keyboard.

**Screenshots and/or hardware setup photos**
[typing issue.zip](https://github.com/FydeOS/chromium_os-raspberry_pi/files/5699973/typing.issue.zip)
Please open this zip file.

**Additional context**
Please comment back to me back when you found how to fix this problem.

**Comment by fydeos-alpha** [comment]
fixed in r86r2 release. Read the full release note though :p
