### ISSUE TITLE
bluetooth mouse not working 

### ISSUE THREAD

**Issue by piotrus22** [FydeOS/chromium_os-raspberry_pi#116]
when i try to connect my logitech bluetooth mouse, it connects but can never move the cursor. when i try to connect the logitech k380 keyboard, it connects but only for 10 seconds then when I tap a key on the keyboard it disconnects.

seems like bluetooth is broken - is that correct? using latest build on my rpi 4b 4gb-

thank you!

**Describe the bug or issue**

**Describe your setup**
 - Your Raspberry Pi model and spec variant, e.g. 4B with 2GB RAM
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS r77 r3
 - Your hardware configuration and setup, e.g. how you have wired the Pi board with any other peripheral connected to it

**To Reproduce**

**Expected behaviour**

**Screenshots and/or hardware setup photos**
If applicable, add screenshots to help explain your problem. If your problem is hardware related, it's much easier to include a photo of how your setup looks like.

**Additional context**

**Comment by wobbo** [comment]
I have the same problem. I have tried it with multiple devices. My mouse Rapoo, Apple mouse, Xbox, Apple keyboard, Maxxrer keyboard. I can add the devices in your list but they keep flashing.

I did manage to connect the LEGO Duplo train app to my train! You have to switch the train and the app on and off a number of times. It is really cool! My child is never allowed to use the train again. lol
