### ISSUE TITLE
Pi-400 wifi not workinig 

### ISSUE THREAD

**Issue by timbo1975** [FydeOS/chromium_os-raspberry_pi#118]
**Describe the bug or issue**
Cannot enable wifi or bluetooth on Pi-400, ethernet is fine. Possibly wifi country code missing?

**Describe your setup**
 - Pi-400 4Gb
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS 86.0.4240.186

**To Reproduce**
1. Go to 'wifi'
2. Click on ''enable'
3. Scroll down to 'wifi networks'
4. No wifi enabled

**Expected behaviour**
Wifi to work

**Comment by fydeos-alpha** [comment]
fixed in r86r2 release.
