### ISSUE TITLE
Google Meet: "Your browser can't share your screen"[Issue report]

### ISSUE THREAD

**Issue by Fusion3Design** [FydeOS/chromium_os-raspberry_pi#123]
you can not share your screen with google meet
open a meeting with google meet, and try to share your screen. you will get a message telling you that your browser can't share your screen

**Comment by andybe** [comment]
seams to me a google problem, because discord web can.

**Comment by andybe** [comment]
> you can not share your screen with google meet
> open a meeting with google meet, and try to share your screen. you will get a message telling you that your browser can't share your screen

seams to me a google problem, because discord web can.
