### ISSUE TITLE
No PlayStore and/or GApps on RPi 400?

### ISSUE THREAD

**Issue by vedranius** [FydeOS/chromium_os-raspberry_pi#124]
**Describe the bug or issue**
I'm trying to install PlayStore and GApps but not sure how to do it.

**Describe your setup**
I'm using latest built image on my RPi 400.

Is there a way to install apps directly from PlayStore or that's not possible on Raspberry Pi boards?

Thanks!

**Comment by fydeos-alpha** [comment]
No - Chromium OS does not have Android subsystems. Chrome OS and FydeOS do.

This project offers Chromium OS.

**Comment by fydeos-alpha** [comment]
@vedranius  https://releases.fydeos.io/11.4/rpi4-fydeos you may want to check out this one, it's FydeOS for You, not Chromium OS, and it supports Android and Linux.
