### ISSUE TITLE
Unable to enable/install Play Store (I'm outside of china)

### ISSUE THREAD

**Issue by andybe** [FydeOS/chromium_os-raspberry_pi#126]
While I know Android is working on the pi 4 and I'm in EU. There is no common thing why I should'nt install Googel PlayStore applications on a rasberry pi 4.

Please make an description. (Not a newbie on linux).

-- https://www.reddit.com/r/chromeos/comments/kk2d56/tutorial_install_android_with_full_graphics/ -- ???
(I wonder this is true)

**Comment by fydeos-alpha** [comment]
the project is for Chromium OS. Not Chrome OS, not FydeOS either. 

Chromium OS does not support Android subsystem, it doesn't concern where you are.

**Comment by andybe** [comment]
sorry  @fydeos-alpha

**Comment by fydeos-alpha** [comment]
> sorry @fydeos-alpha
> 
> hm ... https://github.com/ " FydeOS " /chromium_os-raspberry_p

It suggests that this project is maintained by the FydeOS team, per the README.

**Comment by andybe** [comment]
@fydeos-alpha 

In the official documentation it's written,- found it yesterday
Two nice lines for pi users would be fine:

- Widevine isn't include (most user expected - Kodi etc.)
- Google Appstore not included.

With the reference to the official documentation.
