### ISSUE TITLE
Unable to install linux subsystem - r86r1-rpi4b

### ISSUE THREAD

**Issue by andybe** [FydeOS/chromium_os-raspberry_pi#127]
Virtual Linux can not be started after installation. (stopped at this point as failure)

 - Pi4 - 4GB
 - chromiumos_image_r86r1-rpi4b.img.xz
 - (Userland partition has been expaned to max - 26GB free).

**Comment by fydeos-alpha** [comment]
please re-try with the latest release r86r3

**Comment by Ruffio** [comment]
@andybe has this issue been resolved and can be closed?

**Comment by andybe** [comment]
> @andybe has this issue been resolved and can be closed?

Not yet, working for test on another machine with chrome os. Got it in mind for today.

**Comment by andybe** [comment]
Flash SSD new under gnome.

chromiumos_image_r86r2-rpi4b.img.xz

Looks like it uses the complete drive now per default.

Linux (Beta) works here now.
