### ISSUE TITLE
is it safe to log in with my google account?

### ISSUE THREAD

**Issue by Itai-Nelken** [FydeOS/chromium_os-raspberry_pi#128]

**Comment by fydeos-alpha** [comment]
please define "safe"?

**Comment by fydeos-alpha** [comment]
not an issue, closed here. further comment welcome.

**Comment by Itai-Nelken** [comment]
@fydeos-alpha I remember reading somewhere that you shouldn't log in with your google account, but it might have been a old chromiumOS test image. so I just wanted to be sure.

**Comment by fydeos-alpha** [comment]
Our previous "test" image has a well-known ssh key installed in the system for faster remote connection in the shell level. The warning message regarding this was about shell level credentials, nothing concerning the frontend.

Beginning with the recent releases we don't do test image anymore, you will have to set your own shell user password if you wish to connect to the OS via ssh.

**Comment by Itai-Nelken** [comment]
@fydeos-alpha thanks a lot!
