### ISSUE TITLE
Will Google play store be supported?

### ISSUE THREAD

**Issue by Itai-Nelken** [FydeOS/chromium_os-raspberry_pi#129]
or is there a way to install it?

**Comment by fydeos-alpha** [comment]
not with Chromium OS, unless Google decides to change how things are.

**Comment by fydeos-alpha** [comment]
@Itai-Nelken  https://releases.fydeos.io/11.4/rpi4-fydeos you may want to check out this one, it's FydeOS for You, not Chromium OS, and it supports Android and Linux.

**Comment by Itai-Nelken** [comment]
Great! I'll check it out!

**Comment by Itai-Nelken** [comment]
@fydeos-alpha where can I open a bug report/ask a question about FydeOS for You rpi?
it keeps freezing on my pi4 4gb, sometimes it recovers, and most of the time I have to force reboot it by taking the power out/in.

I'm using a pretty old samsung EVO+ 32gb sd card, could that be the culprit?

**Comment by Itai-Nelken** [comment]
someone?
