### ISSUE TITLE
widevine from official recovery image working in chromium os.

### ISSUE THREAD

**Issue by andybe** [FydeOS/chromium_os-raspberry_pi#130]
Widevine offical not work

 - Your Raspberry Pi model 4B 
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS r86 r2

Found this here:
https://forum.pine64.org/showthread.php?tid=8857

Download:

https://github.com/ayufan-rock64/linux-package/blob/master/root/usr/local/sbin/install_widevine_drm.sh

Installs libwidevine.so and pepper in opt/google/chome:

sudo mount -oremount,rw /

sudo mv Downloads/install_widevine_drm.sh /opt

cd /opt

sudo chmod +x install_widevine_drm.sh
sudo ./install_widevine_drm.sh
sudo rm  ./install_widevine_drm.sh

Reboot.

Tested with
https://bitmovin.com/demos/drm

Amazon Prime, Spotify Web and Netflix.

On my pi 1280x720 watch is film is nice (my thermal problem).

**Comment by ClowdyAllDay** [comment]
how to open a terminal to run those commands?

**Comment by ClowdyAllDay** [comment]
ctrl-alt-t?
