### ISSUE TITLE
Connect with Android phone is not possible

### ISSUE THREAD

**Issue by jordanarpad** [FydeOS/chromium_os-raspberry_pi#131]
On my Raspberry Pi 4B with 4GB RAM running chromiumos_image_r86r2-rpi4b.img.xz I find:
Settings > Connected devices > Android Phone > Connect your Chromebox with your phone > This setting is managed by your administrator.

On contrary, when logging into my personal Google Account that I use to login to Chromium OS also I have:
Your current account, jxxxxxxxxx@gmail.com, isn’t managed by an administrator. The account isn’t associated with any company, school, or group. Instead, it’s a free Google Account that you can manage yourself.

I expected to be able to use Smart Lock on my Android phone to sign in to Chromium OS.

**Comment by fydeos-alpha** [comment]
Features relating to associate your Android phone and the OS isn't available in Chromium OS. The UI displays "managed by Administrator" was, in fact, a kind of irrelevant place holder. We can hide this by modifying Chromium code, but it'd deviate from "vanilla experience". 

Yes, in this case, vanilla is broken.
