### ISSUE TITLE
Android Settings Disappeared

### ISSUE THREAD

**Issue by JayDeeDaz** [FydeOS/chromium_os-raspberry_pi#133]
Following the setup of Android, the "Android Preferences" item within FydeOS Settings has disappeared.

I can open the Android "Settings" app manually, by right clicking an Android app, selecting "App info", and then navigate through the sections. I can then pin the app to the taskbar.

However, on reboot, the pin disappears, and it isn't available in the app drawer.

The built-in app "Android" (which takes me to the Android "Settings" app) no longer works.

Any help will be appreciated.
![Screenshot 2021-01-13 at 18 09 45](https://user-images.githubusercontent.com/3756993/104491764-99fa3b00-55ca-11eb-87ac-5916876714ba.png)

**Comment by fydeos-alpha** [comment]
This project does not concern FydeOS. Sorry mate, wrong place.
