### ISSUE TITLE
Disable rpi4 onboard Wifi through overlay or blacklist?

### ISSUE THREAD

**Issue by pbohannon** [FydeOS/chromium_os-raspberry_pi#136]
Hi there.  First of all, GREAT WORK on this - both the distribution and the documentation are outstanding!  Thank you for working on this project.

I am curious how to disable the onboard Wifi on my Pi4 during a manual build of ChromeOS/Chrome, using the overlays and Chrome customizations from FydeOS.  Using a standard Pi installation, I would do one or both of : 1/ use the dtoverlay=disable-wifi stanza in config.txt, and/or 2/ blacklist brcmfmac in /etc/modules.d/blacklist-wifi.conf (or something similar).  

I have gone through the overlays directories and do not see the disable-wifi (nor disable-bt) DTB files, so I suspect option #1 above will not work. Could I somehow blacklist the brcmfmac driver that enables the onboard Wifi before or even after my build?

Thanks very much!

**Comment by fydeos-alpha** [comment]
config.txt is located under `overlay-rpi4`, you could change it before building. If it's a pre-built image, it's located in partition 12.
