### ISSUE TITLE
Pi 3 B+ : Distorted Screen on Boot

### ISSUE THREAD

**Issue by midhunvnadh** [FydeOS/chromium_os-raspberry_pi#14]
I am Getting a Distorted Screen on Boot. I am guessing that there are clickable items / Buttons Below the Distorted Screen. It is a display issue ?. Do I need to edit in the config.txt file ?. Please Help

**Comment by midhunvnadh** [comment]
AOC E1670SWU 15.6-inch LED Monitor
Connection via HDMI to monitor, Pi power supply.
It's the Pi 3 B+ Itself.

How can I get to the dmesg log ?
Photo Uploaded.
![20190129_004122](https://user-images.githubusercontent.com/32438353/51860605-36848d80-2360-11e9-9cc4-40c43787897a.jpg)

**Comment by yunshansimon** [comment]
Does your monitor work with official Rasbian?

**Comment by midhunvnadh** [comment]
Yes. It works !. Fantastically !.

**Comment by midhunvnadh** [comment]
Guys !. Help Please

**Comment by yunshansimon** [comment]
Try comment “hdmi_drive=2” in config.txt at /dev/sda12

**Comment by tresni** [comment]
I'm having the same issue, commented out `hdmi_drive=2` in config.txt and tried again, same results.  My TV is a Vizio E320-B0.  Works fine with Rasbian (my normal config.txt for Raspbian
 only has `dtparam=audio=on` and nothing else.)  I'm not sure what's safe to comment out in the config.txt to continue testing.

![img_8652](https://user-images.githubusercontent.com/210250/52171154-19134300-2715-11e9-9606-0196272fbd5e.jpg)

**Comment by midhunvnadh** [comment]
No luck to me too :(

**Comment by akavkl** [comment]
Dev/sda12 not found on r72

**Comment by benklop** [comment]
what's strange is when this happens for my brother's install, the mouse cursor is not distorted

**Comment by raynmune** [comment]
Same issue here. Monitor distorted like @tresni and mouse cursor not distorted, can play around clicking and distort changes

**Comment by sidifal** [comment]
any body have solution!!

**Comment by sincoew** [comment]
same issue +1

**Comment by tresni** [comment]
Just as a note, I plugged the rPI into a standard monitor and it worked.  I ended up giving up on trying to make this work on the TV.

**Comment by LCCR193** [comment]
> Just as a note, I plugged the rPI into a standard monitor and it worked. I ended up giving up on trying to make this work on the TV.

Well, but on the monitor I have it is distoted, (resolution 1366x768@60hz, 18.5")

**Comment by muratcesmecioglu** [comment]
same here. please help.

**Comment by 16110267** [comment]
hi i have this issue too, anyone know how to fix this issue?

**Comment by muratcesmecioglu** [comment]
> hi i have this issue too, anyone know how to fix this issue?

I just tried another (and worse) monitor with default installation and it worked. :)
