### ISSUE TITLE
Broken Audio / Video when connecting a Bluetooth speaker

### ISSUE THREAD

**Issue by sonykappithan** [FydeOS/chromium_os-raspberry_pi#140]
While connecting a bluetooth speaker audio and video playing with a pause in each second

**Comment by fydeos-alpha** [comment]
The reason for this to happen is the audio stream requires a sampling process before it's sent to your Bluetooth speaker, this process is apparently resources-intensive and shares the same hardware encoder as decoding the video stream.

Raspberry Pi does not have the best media processing ability I am afraid, it's too much of an ask for the Pi to stream video whilst re-sample the audio and stream it via BT at the same time.
