### ISSUE TITLE
Dual monitor on 400 broken

### ISSUE THREAD

**Issue by janat08** [FydeOS/chromium_os-raspberry_pi#145]
Dual monitor on 400 image (1gb+) is broken. Setting hdmi safe makes resolution go to the lowest possible value.

**Comment by mbodomi** [comment]
I dont want to open other issue
I have Pi400
flashed this image FydeOS_for_you_Pi400_v11.4_SP2.img.xz =) 
This image and sadly it has a diagonally streched screen on my monitor setup
How do I fix it?

**Comment by mbodomi** [comment]
I have a 720p BENQ LCD with DVI

**Comment by janat08** [comment]
Yea more specifically the second monitor ranges from being recognized by OS, but giving blank screen on one of the two (I think), to entirely ignoring the second one. I have junk monitors from 2000s.

**Comment by mbodomi** [comment]
So you are using hdmi->vga converters?

**Comment by janat08** [comment]
Yes

**Comment by goalhelp** [comment]
> I dont want to open other issue
> I have Pi400
> flashed this image: FydeOS_for_you_Pi400_v11.4_SP2.img.xz =)
> ;; and sadly it has a diagonally streched screen on my monitor setup
> How do I fix it?

you can fix this issue with this 
hdmi_ignore_edid=0xa5000080

edit the below config accordig to your monitor or tv
hdmi_group=2
hdmi_mode=85
hdmi_force_plug=1
