### ISSUE TITLE
[Issue report] Enable debug serial port on FydeOS

### ISSUE THREAD

**Issue by ColinWang1203** [FydeOS/chromium_os-raspberry_pi#151]
**Describe the bug or issue**
Hello, Is there a way to enable the debug boot log like RPI-OS?
On RPI-OS we can use USB to TTL and connect the uart to get the boot log.
Is there a similar way we can achieve this on the FydeOS?
I tried to add the "USE=pcserial" when building the packages and images but it wont work.
Really like this project and want to dig futher into this kernel, will be greatly appreciated if any help!

**Describe your setup**
 - 4B with 4GB RAM
 - Chromium OS r86
 - USB to TTL connected on the Gnd gpio14 and gpio15 on rpi

Also I used the --force option when flashing, but the partition 1 still fails to flash?
Although this does not affect the boot up:
![Screenshot from 2021-03-14 19-12-08](https://user-images.githubusercontent.com/29390128/111066318-615add00-84f9-11eb-8f20-8ee3cbe9a39b.png)

**To Reproduce**
flash image and boot, no log on the /dev/ttyUSB0

**Expected behavior**
log is visible via putty serial port

**Screenshots and/or hardware setup photos**

![PXL_20210314_102839331](https://user-images.githubusercontent.com/29390128/111065978-949c6c80-84f7-11eb-94a2-06367b525e45.jpg)

**Additional context**
Thanks!

**Comment by ColinWang1203** [comment]
Any support? Really need to run this as an important project.

**Comment by yunshansimon** [comment]
You need to modify the config.txt on EFI partition (the 12th partition on disk). 
```
mkdir /tmp/sdb12
sudo mount /dev/sdb12 /tmp/sdb12
sudo sh -c "echo   'enable_uart=1' >> /tmp/sdb12/config.txt"
sudo umount /dev/sdb12
```
/dev/sdb12 as the 12th of your usb disk.

Or you can modify the config.txt file at `overlay-rpi4/chromeos-base/chromeos-bsp-rpi4/files/kernel-config` , and remerge the package by ` emerge-rpi4 chromeos-bsp-rpi4` . Then rebuild the image. You will get an "uart enabled" image.

**Comment by ColinWang1203** [comment]
> You need to modify the config.txt on EFI partition (the 12th partition on disk).
> 
> ```
> mkdir /tmp/sdb12
> sudo mount /dev/sdb12 /tmp/sdb12
> sudo sh -c "echo   'enable_uart=1' >> /tmp/sdb12/config.txt"
> sudo umount /dev/sdb12
> ```
> 
> /dev/sdb12 as the 12th of your usb disk.
> 
> Or you can modify the config.txt file at `overlay-rpi4/chromeos-base/chromeos-bsp-rpi4/files/kernel-config` , and remerge the package by ` emerge-rpi4 chromeos-bsp-rpi4` . Then rebuild the image. You will get an "uart enabled" image.

Hello yunshansimon,

Thanks for your reply,

I tried to uncomment the enable_uart=1 in the config.txt and rebuild&flash the image,
but kernel panic happens and I could not solve it for these days,
Would you mind look into it?

=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2021.03.19 20:37:51 =~=~=~=~=~=~=~=~=~=~=~=
10fd083]
[    0.000000] Linux version 5.4.74-v8-g7341321b8bbb (colin@colin-UX410UQK) (Chromium OS 11.0_pre394483_p20200618-r9 clang version 11.0.0 (/var/cache/chromeos-cache/distfiles/egit-src/llvm-project b726d071b4aa46004228fc38ee5bfd167f999bfe)) #3 SMP PREEMPT Fri Mar 19 08:27:27 CST 2021
[    0.000000] Machine model: Raspberry Pi 4 Model B Rev 1.2
[    0.000000] efi: Getting EFI parameters from FDT:
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x000000001ec00000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] percpu: Embedded 30 pages/cpu s85400 r8192 d29288 u122880
[    0.000000] Detected PIPT I-cache on CPU0
[    0.000000] CPU features: detected: EL2 vector hardening
[    0.000000] ARM_SMCCC_ARCH_WORKAROUND_1 missing from firmware
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 996912
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1  smsc95xx.macaddr=DC:A6:32:9F:6A:EA vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  coherent_pool=6M smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 console=ttyS0,115200 earlyprintk=ttyS0,115200 log_level=7 root=PARTUUID=45960909-72D1-D84F-BBCD-4642FD907AD0 rootfstype=ext2 rootwait ro cros_debug cros_secure elevator=deadline
[    0.000000] Dentry cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
[    0.000000] Inode-cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] software IO TLB: mapped [mem 0x37400000-0x3b400000] (64MB)
[    0.000000] Memory: 3627096K/4050944K available (9468K kernel code, 894K rwdata, 3000K rodata, 960K init, 929K bss, 161704K reserved, 262144K cma-reserved)
[    0.000000] random: get_random_u64 called from __kmem_cache_create+0xb4/0x598 with crng_init=0
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 31291 entries in 123 pages
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000] 	Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] arch_timer: cp15 timer(s) running at 54.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xc743ce346, max_idle_ns: 440795203123 ns
[    0.000005] sched_clock: 56 bits at 54MHz, resolution 18ns, wraps every 4398046511102ns
[    0.000165] Calibrating delay loop (skipped), value calculated using timer frequency.. 108.00 BogoMIPS (lpj=216000)
[    0.000186] pid_max: default: 32768 minimum: 301
[    0.000367] LSM: Security Framework initializing
[    0.000396] Yama: becoming mindful.
[    0.000430] LoadPin: ready to pin (currently not enforcing)
[    0.000648] Mount-cache hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.000697] Mountpoint-cache hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.002850] ASID allocator initialised with 32768 entries
[    0.003042] rcu: Hierarchical SRCU implementation.
[    0.003621] EFI services will not be available.
[    0.004130] smp: Bringing up secondary CPUs ...
[    0.004969] Detected PIPT I-cache on CPU1
[    0.005025] CPU1: Booted secondary processor 0x0000000001 [0x410fd083]
[    0.005999] Detected PIPT I-cache on CPU2
[    0.006036] CPU2: Booted secondary processor 0x0000000002 [0x410fd083]
[    0.006957] Detected PIPT I-cache on CPU3
[    0.006995] CPU3: Booted secondary processor 0x0000000003 [0x410fd083]
[    0.007138] smp: Brought up 1 node, 4 CPUs
[    0.007173] SMP: Total of 4 processors activated.
[    0.007188] CPU features: detected: 32-bit EL0 Support
[    0.007202] CPU features: detected: CRC32 instructions
[    0.007288] CPU: All CPU(s) started at EL2
[    0.007336] alternatives: patching kernel code
[    0.008850] devtmpfs: initialized
[    0.018788] Enabled cp15_barrier support
[    0.018824] Enabled setend support
[    0.019292] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.019319] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.025840] pinctrl core: initialized pinctrl subsystem
[    0.026480] DMI not present or invalid.
[    0.026829] NET: Registered protocol family 16
[    0.029775] DMA: preallocated 6144 KiB pool for atomic allocations
[    0.029825] audit: initializing netlink subsys (disabled)
[    0.030108] audit: type=2000 audit(0.028:1): state=initialized audit_enabled=0 res=1
[    0.030674] cpuidle: using governor ladder
[    0.030917] cpuidle: using governor menu
[    0.031141] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.031349] Serial: AMBA PL011 UART driver
[    0.034393] bcm2835-mbox fe00b880.mailbox: mailbox enabled
[    0.044138] raspberrypi-firmware soc:firmware: Attached to firmware from 2020-10-22 14:00, variant start_db
[    0.048144] raspberrypi-firmware soc:firmware: Firmware hash is 74e754ff8947c58d2773253f77f6f68a303188f8
[    0.085343] cryptd: max_cpu_qlen set to 1000
[    0.089255] bcm2835-dma fe007000.dma: DMA legacy API manager, dmachans=0x1
[    0.093217] SCSI subsystem initialized
[    0.093414] usbcore: registered new interface driver usbfs
[    0.093468] usbcore: registered new interface driver hub
[    0.093596] usbcore: registered new device driver usb
[    0.093862] Advanced Linux Sound Architecture Driver Initialized.
[    0.094810] clocksource: Switched to clocksource arch_sys_counter
[    0.155740] VFS: Disk quotas dquot_6.6.0
[    0.155854] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.157477] thermal_sys: Registered thermal governor 'step_wise'
[    0.157858] NET: Registered protocol family 2
[    0.158563] tcp_listen_portaddr_hash hash table entries: 2048 (order: 3, 32768 bytes, linear)
[    0.158607] TCP established hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.158854] TCP bind hash table entries: 32768 (order: 7, 524288 bytes, linear)
[    0.159227] TCP: Hash tables configured (established 32768 bind 32768)
[    0.159420] UDP hash table entries: 2048 (order: 4, 65536 bytes, linear)
[    0.159476] UDP-Lite hash table entries: 2048 (order: 4, 65536 bytes, linear)
[    0.159745] NET: Registered protocol family 1
[    0.159788] PCI: CLS 0 bytes, default 64
[    0.161306] hw perfevents: enabled with armv8_cortex_a72 PMU driver, 7 counters available
[    0.161534] kvm: Limiting the IPA size due to kernel Virtual Address limit
[    0.161548] kvm [1]: IPA Size Limit: 43bits
[    0.162253] kvm [1]: vgic interrupt IRQ1
[    0.162471] kvm [1]: Hyp mode initialized successfully
[    0.164621] Initialise system trusted keyrings
[    0.164920] workingset: timestamp_bits=62 max_order=20 bucket_order=0
[    0.173412] Registering esdfs 0.2
[    0.195150] Key type asymmetric registered
[    0.195166] Asymmetric key parser 'x509' registered
[    0.195226] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    0.195241] io scheduler mq-deadline registered
[    0.195255] io scheduler kyber registered
[    0.195398] io scheduler bfq registered
[    0.198474] brcm-pcie fd500000.pcie: host bridge /scb/pcie@7d500000 ranges:
[    0.198501] brcm-pcie fd500000.pcie:   No bus range found for /scb/pcie@7d500000, using [bus 00-ff]
[    0.198561] brcm-pcie fd500000.pcie:      MEM 0x0600000000..0x0603ffffff -> 0x00f8000000
[    0.198620] brcm-pcie fd500000.pcie:   IB MEM 0x0000000000..0x00bfffffff -> 0x0000000000
[    0.248911] brcm-pcie fd500000.pcie: link up, 5 GT/s x1 (SSC)
[    0.249221] brcm-pcie fd500000.pcie: PCI host bridge to bus 0000:00
[    0.249241] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.249261] pci_bus 0000:00: root bus resource [mem 0x600000000-0x603ffffff] (bus address [0xf8000000-0xfbffffff])
[    0.249313] pci 0000:00:00.0: [14e4:2711] type 01 class 0x060400
[    0.249530] pci 0000:00:00.0: PME# supported from D0 D3hot
[    0.253092] pci 0000:01:00.0: [1106:3483] type 00 class 0x0c0330
[    0.253232] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x00000fff 64bit]
[    0.253651] pci 0000:01:00.0: PME# supported from D0 D3cold
[    0.256894] pci 0000:00:00.0: BAR 8: assigned [mem 0x600000000-0x6000fffff]
[    0.256918] pci 0000:01:00.0: BAR 0: assigned [mem 0x600000000-0x600000fff 64bit]
[    0.256996] pci 0000:00:00.0: PCI bridge to [bus 01]
[    0.257019] pci 0000:00:00.0:   bridge window [mem 0x600000000-0x6000fffff]
[    0.257122] pci 0000:00:00.0: enabling device (0000 -> 0002)
[    0.257182] pci 0000:01:00.0: enabling device (0000 -> 0002)
[    0.261077] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    0.263283] iproc-rng200 fe104000.rng: hwrng registered
[    0.263808] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.264563] gpiomem-bcm2835 fe200000.gpiomem: Initialised: Registers at 0xfe200000
[    0.270035] [drm] No displays found. Consider forcing hotplug if HDMI is attached
[    0.270074] vc4-drm gpu: bound fe600000.firmwarekms (ops vc4_fkms_ops)
[    0.270092] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    0.270104] [drm] No driver support for vblank timestamp query.
[    0.270116] [drm] Setting vblank_disable_immediate to false because get_vblank_timestamp == NULL
[    0.270468] [drm] Initialized vc4 0.0.0 20140616 for gpu on minor 0
[    0.270487] [drm] signed vc4_drm_file
[    0.270493] [drm] signed vc4_drm
[    0.271162] [drm] Initialized vgem 1.0.0 20120112 for vgem on minor 1
[    0.271416] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.281479] brd: module loaded
[    0.288325] loop: module loaded
[    0.289475] Loading iSCSI transport class v2.0-870.
[    0.291352] libphy: Fixed MDIO Bus: probed
[    0.291862] bcmgenet fd580000.ethernet: failed to get enet clock
[    0.291882] bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
[    0.291904] bcmgenet fd580000.ethernet: failed to get enet-wol clock
[    0.291923] bcmgenet fd580000.ethernet: failed to get enet-eee clock
[    0.291949] bcmgenet: Skipping UMAC reset
[    0.302835] libphy: bcmgenet MII bus: probed
[    0.350903] unimac-mdio unimac-mdio.-19: Broadcom UniMAC MDIO bus
[    0.351831] usbcore: registered new interface driver r8152
[    0.351890] usbcore: registered new interface driver lan78xx
[    0.351942] usbcore: registered new interface driver smsc95xx
[    0.352403] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    0.352435] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 1
[    0.353397] xhci_hcd 0000:01:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0000003000000890
[    0.354591] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    0.354610] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.354626] usb usb1: Product: xHCI Host Controller
[    0.354641] usb usb1: Manufacturer: Linux 5.4.74-v8-g7341321b8bbb xhci-hcd
[    0.354655] usb usb1: SerialNumber: 0000:01:00.0
[    0.355293] hub 1-0:1.0: USB hub found
[    0.355384] hub 1-0:1.0: 1 port detected
[    0.356005] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    0.356029] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 2
[    0.356055] xhci_hcd 0000:01:00.0: Host supports USB 3.0 SuperSpeed
[    0.356491] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.04
[    0.356509] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.356524] usb usb2: Product: xHCI Host Controller
[    0.356538] usb usb2: Manufacturer: Linux 5.4.74-v8-g7341321b8bbb xhci-hcd
[    0.356552] usb usb2: SerialNumber: 0000:01:00.0
[    0.357100] hub 2-0:1.0: USB hub found
[    0.357165] hub 2-0:1.0: 4 ports detected
[    0.358497] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.359317] usbcore: registered new interface driver uas
[    0.359404] usbcore: registered new interface driver usb-storage
[    0.359626] mousedev: PS/2 mouse device common for all mice
[    0.360864] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    0.361269] device-mapper: ioctl: 4.41.0-ioctl (2019-09-16) initialised: dm-devel@redhat.com
[    0.365976] sdhci: Secure Digital Host Controller Interface driver
[    0.365985] sdhci: Copyright(c) Pierre Ossman
[    0.366251] mmc-bcm2835 fe300000.mmcnr: could not get clk, deferring probe
[    0.366440] Error: Driver 'sdhost-bcm2835' is already registered, aborting...
[    0.366445] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.368608] ledtrig-cpu: registered to indicate activity on CPUs
[    0.368671] hidraw: raw HID events driver (C) Jiri Kosina
[    0.368741] usbcore: registered new interface driver usbhid
[    0.368747] usbhid: USB HID core driver
[    0.369617] vchiq: vchiq_init_state: slot_zero = (____ptrval____)
[    0.372400] Initializing XFRM netlink socket
[    0.372420] NET: Registered protocol family 17
[    0.372456] Key type dns_resolver registered
[    0.372662] registered taskstats version 1
[    0.372673] Loading compiled-in X.509 certificates
[    0.372832] Key type ._fscrypt registered
[    0.372839] Key type .fscrypt registered
[    0.373452] Key type encrypted registered
[    0.377849] uart-pl011 fe201000.serial: cts_event_workaround enabled
[    0.377905] fe201000.serial: ttyAMA0 at MMIO 0xfe201000 (irq = 14, base_baud = 0) is a PL011 rev2
[    0.382126] printk: console [ttyS0] disabled
[    0.382159] fe215040.serial: ttyS0 at MMIO 0x0 (irq = 15, base_baud = 62500000) is a 16550
[    1.635292] printk: console [ttyS0] enabled
[    1.640602] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    1.648363] mmc-bcm2835 fe300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    1.654473] mmc-bcm2835 fe300000.mmcnr: DMA channel allocated
[    1.703491] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    1.710577] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.717664] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.725959] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    1.731538] mmc0: SDHCI controller on fe340000.emmc2 [fe340000.emmc2] using ADMA
[    1.742380] [drm] Initialized v3d 1.0.0 20180419 for fec00000.v3d on minor 2
[    1.750058] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.756978] of_cfs_init
[    1.759483] of_cfs_init: OK
[    1.762638] ALSA device list:
[    1.765807]   No soundcards found.
[    1.769550] Waiting for root device PARTUUID=45960909-72D1-D84F-BBCD-4642FD907AD0...
[    1.817612] random: fast init done
[    1.839610] mmc1: new high speed SDIO card at address 0001
[    1.882810] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[    1.891584] mmc0: new ultra high speed DDR50 SDHC card at address aaaa
[    1.898743] mmcblk0: mmc0:aaaa SB32G 29.7 GiB
[    1.910766] GPT:Primary header thinks Alt. header is not at the end of the disk.
[    1.918292] GPT:10903708 != 62333951
[    1.921918] GPT:Alternate GPT header not at the end of the disk.
[    1.928013] GPT:10903708 != 62333951
[    1.931639] GPT: Use GNU Parted to correct GPT errors.
[    1.936872]  mmcblk0: p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12
[    1.953527] EXT4-fs (mmcblk0p3): mounting ext2 file system using the ext4 subsystem
[    1.968018] EXT4-fs (mmcblk0p3): mounted filesystem without journal. Opts: (null)
[    1.975655] VFS: Mounted root (ext2 filesystem) readonly on device 179:3.
[    1.988618] devtmpfs: mounted
[    1.993428] Freeing unused kernel memory: 960K
[    1.998010] Run /sbin/init as init process
/sbin/in[    2.037338] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
it: erro[    2.041461] usb 1-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.21
[    2.045739] CPU: 3 PID: 1 Comm: init Not tainted 5.4.74-v8-g7341321b8bbb #3
r while [    2.045741] Hardware name: Raspberry Pi 4 Model B Rev 1.2 (DT)
[    2.045743] Call trace:
loading [    2.045755]  dump_backtrace+0x0/0x144
[    2.045760]  show_stack+0x20/0x2c
[    2.054747] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    2.061790]  dump_stack+0xbc/0x150
[    2.061794]  panic+0x150/0x35c
[    2.061797]  exit_mm+0x0/0x1c8
[    2.061799]  __arm64_sys_exit_group+0x0/0x30
[    2.061802]  __arm64_sys_exit_group+0x20/0x30
[    2.068415] usb 1-1: Product: USB2.0 Hub
[    2.070876]  el0_svc_common+0xac/0x198
[    2.070880]  el0_svc_compat_handler+0x2c/0x40
[    2.070882]  el0_svc_compat+0x8/0x10
[    2.070889] SMP: stopping secondary CPUs
[    2.076389] hub 1-1:1.0: USB hub found
[    2.078642] Kernel Offset: disabled
[    2.078645] CPU features: 0x0002,20006000
[    2.078647] Memory Limit: none
[    2.138429] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00 ]---
