### ISSUE TITLE
Apple M1 silicon support

### ISSUE THREAD

**Issue by erseco** [FydeOS/chromium_os-raspberry_pi#153]
This build for arm is compatible with arm64? Would be nice to use in the parallels virtual machine beta to run virtualized on the new M1 arch

Best

**Comment by fydeos-alpha** [comment]
yes, it'd be nice, but unless Apple commission us to do this, it's unlikely that we will commit to the porting 🤔

**Comment by qq597353** [comment]
I need fydeos of apple cpu
