### ISSUE TITLE
Linux (Beta) can not be installed in the new Chromium r89r1

### ISSUE THREAD

**Issue by KarlJoachim** [FydeOS/chromium_os-raspberry_pi#158]
**Describe the bug or issue**

**Describe your setup**
 - Your Raspberry Pi model and spec variant, e.g. 4B with 2GB RAM
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS r77 r3
 - Your hardware configuration and setup, e.g. how you have wired the Pi board with any other peripheral connected to it

**To Reproduce**

**Expected behaviour**

**Screenshots and/or hardware setup photos**
If applicable, add screenshots to help explain your problem. If your problem is hardware related, it's much easier to include a photo of how your setup looks like.

**Additional context**

**Comment by mdali7053** [comment]
My raspberry pi 4b 2Gb install linux but error why

**Comment by KarlJoachim** [comment]
I have repeated the installation of Chromium r89r1 and the Linux (beta) cannot be installed. It ends with an error. I use an Raspberry 4B with 8 GB RAM an a 32 GB sd-Card. I have made same pictures showing the disk space an the other windows during the installation of the Linux environement.
![IMG_20210509_150922](https://user-images.githubusercontent.com/83031535/117573952-a7629600-b08f-11eb-9637-a4cb5b126e60.jpg)
![IMG_20210509_151044](https://user-images.githubusercontent.com/83031535/117573958-b6494880-b08f-11eb-9a53-62e2093445bd.jpg)
![IMG_20210509_151018](https://user-images.githubusercontent.com/83031535/117573990-eabd0480-b08f-11eb-8b97-a432350a68bf.jpg)
![IMG_20210509_151125](https://user-images.githubusercontent.com/83031535/117574010-f7d9f380-b08f-11eb-971b-83c9cc3fd138.jpg)

**Comment by yunshansimon** [comment]
The Linux environment needs 4G memory/ 4G free hard disk space at least. The chromium OS for rpi needs downloading 1G binary from google's server, pls check your internet connection.

**Comment by thepolarbear0818** [comment]
I have the same issue, with an 8G ram RPI and a 16G SD card, I have internet, but it will always fail on creating a disk. I tried this many times by re-writing the image to the sd card. It will not word. It did work on the last version though, so it's probable only this version that's affected.

**Comment by NonstickAtom785** [comment]
This actually has nothing to do with the build itself. This is an issue with chromium os itself. Just wait until the next full dev build and it should be fixed.

**Comment by KarlJoachim** [comment]
Ok. Thank you. The Linux environment in the r86r2 version is a very good feature, I like it.

**Comment by tkchakos** [comment]
I am also having this. I have 8 GB of RAM & 425 GB of free disk space. I will wait for the next update. Thank you!

**Comment by sindelar-fr** [comment]
Is there some plan on when the next release that will fix this will be? (October-ish?)

**Comment by fydeos-alpha** [comment]
@sindelar-fr  working on that right now, stay tuned

**Comment by fydeos-alpha** [comment]
Unfortunately we don't have plan to fix this for r89. It'll be fixed in r92 which is our next major release. For the time being, you guys can try FydeOS for You - Raspberry Pi 400 which has a working Crostini.
