### ISSUE TITLE
[Issue report]

### ISSUE THREAD

**Issue by rpangrazio** [FydeOS/chromium_os-raspberry_pi#161]
**Describe the bug or issue**
Bluetooth keyboard and bluetooth mouse pairs but inputs are not recognized

**Describe your setup**
 - 4B 4Gb ram
 - R89-r1
 - Lenovo LEN T2254 Monitor
 - Microsoft Wedge Mobile Bluetooth Keyboard
 - Microsoft Designer Bluetooth Mouse Model 1679

1 - Attempt to connect bluetooth Keyboard/Mouse
2 - Device Pairs
3 - No inputs are recognized

**Expected behavior**
Recognize inputs

**Comment by fydeos-alpha** [comment]
We don't have your specific make/model of the Bluetooth keyboard/mouse, when we test the build using our Bluetooth mouse (Mi Portable Mouse) it worked.
