### ISSUE TITLE
Enable the virtual keyboard on the login screen

### ISSUE THREAD

**Issue by mauricemu** [FydeOS/chromium_os-raspberry_pi#162]
Describe the bug or issue
Cannot find virtual keyboard on the login screen

Describe your setup
Raspad rpi 4 8GB 
chromiumos release r89

To Reproduce
start Raspad or Raspberry pi

Additional Information:
Virtual keyboard is enabled and after login also accessible.

**Comment by tkchakos** [comment]
This is working on mine.  R Pi 4 with 8 GB RAM & 425 GB disk.

**Comment by fydeos-alpha** [comment]
can't reproduce on our test bed either. You can reopen this issue if you supply more info
