### ISSUE TITLE
berryboot compatible

### ISSUE THREAD

**Issue by milindkagit** [FydeOS/chromium_os-raspberry_pi#166]
I learnt about fydeos and willing to install it on my device, berryboot is a great way of reliably and repeatably installing multiple OSes on one (raspberry) device. 

https://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions
Steps here assume two partitions, however FydeOS_for_you_Pi400_v11.4_SP2.img shows 12 Partition table entries.  Their documentation does not advise how to convert for fydeOS scenario,

Please share squash fs compatible image or advise the instructions to convert fydeos img to berryboot (squashfs) format.

**Comment by fydeos-alpha** [comment]
this project only concerns Chromium OS for Raspberry Pi. You were asking FydeOS for You, therefore you are in the wrong place. 

Please refer to the FAQ in the README.
