### ISSUE TITLE
Google Drive missing from Files Manager

### ISSUE THREAD

**Issue by tkchakos** [FydeOS/chromium_os-raspberry_pi#173]
Version 89.0.4389.82 (Official Build) (32-bit)
Running on Raspberry Pi 4 with 8 GB of ram.

The Files App does not show any way to add or link to the Google Drive. To save a file to the drive, I need to save it locally then upload it back to the drive. Can we fix that?

Thanks!
![Screenshot 2021-07-07 11 29 21 AM](https://user-images.githubusercontent.com/87091883/124810811-9f4f9700-df16-11eb-8879-609a7d212a91.png)

**Comment by fydeos-alpha** [comment]
No, Google Drive dependencies are currently proprietary and therefore not included in Chromium OS.
