### ISSUE TITLE
Open Gapps Not Working

### ISSUE THREAD

**Issue by UKBALL** [FydeOS/chromium_os-raspberry_pi#176]
I have a problem with OpenGapps. It says, "Your FydeOS does not support this action. Please consider upgrading FydeOS.", although I didn't know what they meant by 'upgrade'. However, I did update my FydeOS, and also enabled Andriod.

I am currently using a Raspberry Pi 4, 8GB of RAM, with 200 gb of storage space.

**Comment by fydeos-alpha** [comment]
This project does not concern FydeOS. Please read the FAQ section in README.

**Comment by ojczeo** [comment]
Checkout out this custom solution:
https://www.youtube.com/watch?v=3y4FKdyv3T4&t=379s
