### ISSUE TITLE
Constant Crashing on newest build

### ISSUE THREAD

**Issue by Scriptyure** [FydeOS/chromium_os-raspberry_pi#18]
When I start up the device it allows me to login before crashing and restarting the system. I'm going to try the previous build soon as it may just be my device or sd card.
Edit: Previous os wont even get to start screen, it just gets stuck looping the colors startup

**Comment by StuartIanNaylor** [comment]
https://github.com/FydeOS/chromium_os_for_raspberry_pi/releases/download/r72/chromiumos_image_r72.img.xz On a Pi3b seems to work well.

**Comment by swapanshridhar** [comment]
> https://github.com/FydeOS/chromium_os_for_raspberry_pi/releases/download/r72/chromiumos_image_r72.img.xz On a Pi3b seems to work well.

Tried the r72 too. This too reboots as soon as i select some file.

**Comment by yunshansimon** [comment]
Check your power supply, replace it with a stable one. It needs more power than official raspbian(initial the GPU at the booting).

**Comment by fydeos-alpha** [comment]
bulk closure of dated issues

**Comment by rslashpuzzleheadedact** [comment]
Your desktop pc is incompatible I used to have a hp desktop that was not compatible one laptop that works is 300$ its the lenovo ideapad 3. press f12 to boot menu and f2 for bios.

**Comment by Damenly** [comment]
> Your desktop pc is incompatible I used to have a hp desktop that was not compatible one laptop that works is 300$ its the lenovo ideapad 3. press f12 to boot menu and f2 for bios.

Sorry. It’s an issue board of chromiumos rpi. I’m confused why you talked about PC?

**Comment by Scriptyure** [comment]
> > Your desktop pc is incompatible I used to have a hp desktop that was not compatible one laptop that works is 300$ its the lenovo ideapad 3. press f12 to boot menu and f2 for bios.
> 
> Sorry. It’s an issue board of chromiumos rpi. I’m confused why you talked about PC?

Not to mention this has been necroed from 4 years ago
