### ISSUE TITLE
camera is currently unavaliable 

### ISSUE THREAD

**Issue by simonevetere** [FydeOS/chromium_os-raspberry_pi#180]
Describe the bug or issue
Cant connect module raspberry camera, when i open camera said "You camera is currently unavaliable"

Describe your setup

Raspberry Pi 4 Model
Fyde OS
Module Camera Raspberry
To Reproduce

Open Camera
Expected behaviour
when i open camera said "You camera is currently unavaliable", i already put my camera. 

Can i fix with Qv4l2 driver for linux ?

**Comment by fydeos-alpha** [comment]
it's a known issue and we will be fixing it on the next major release with the help of libcamera

**Comment by simonevetere** [comment]
I am a Java developer, can I help you in exchange for the commercial
license?

Il lun 9 ago 2021, 06:46 fydeos-alpha ***@***.***> ha scritto:
