### ISSUE TITLE
Disable Kiosk mode

### ISSUE THREAD

**Issue by mintbridge** [FydeOS/chromium_os-raspberry_pi#181]
Hi, i followed the instructions in the release note and they worked perfectly. How do i disable the kiosk mode now though? Ideally at boot so that i can login to the user account if needed

**Comment by fydeos-alpha** [comment]
You are asking for a feature that belongs to FydeOS Enterprise Upgrade. With this release of Chromium OS for Raspberry Pi, you can only undo what you did with the `chrome_dev.conf` and `system-services.override` to manually disable "forced" kiosk mode.
