### ISSUE TITLE
chrome://flags Page is blank/empty on r92 release

### ISSUE THREAD

**Issue by carlosg2** [FydeOS/chromium_os-raspberry_pi#184]
Unable to use chrome://flags page on r92 release.
Displays blank/empty list, only the search field and reset button are shown.

**Setup**
Raspberry Pi 4B with 8GB RAM
Chromium OS for Raspberry Pi r92 r1

**To Reproduce**
1. Open Chromium browser
2. Navigate to 'chrome://flags'
3. Flags page is displayed with an empty list, only the search field and reset button are shown
(same result under incognito mode)

**Expected behaviour**
Display a list of flags available for Chromium OS/browser.  

**Additional info**
A quick google search for 'chrome flags empty' shows problem with chrome os in the past related to TPM (Trusted Platform Module) but i cannot confirm.

Screenshot:
![Screenshot 2021-08-25 04 18 38](https://user-images.githubusercontent.com/212313/130766010-0c3696cb-29a3-4e13-b941-0f78b03fdf2f.png)

**Comment by 5erade** [comment]
Exact same problem...

**Comment by fydeos-alpha** [comment]
fixed, try r92-r2 release
