### ISSUE TITLE
Chromium OS r92r1 - No access to the Linux directory from the file manager 

### ISSUE THREAD

**Issue by KarlJoachim** [FydeOS/chromium_os-raspberry_pi#185]
After creating the SD-Card (32GB) with the r92r1 image file I booted the chromium OS on a Paspberry 4B with 4 GB RAM.
Then I expanded the partition:

1) Open the terminal in the chrome browser with CTRL + ALT + T
2) Start a shell with: shell
2) Expand the partition with: sudo /usr/sbin/expand-partition.sh -d $(findmnt -n -o source /mnt/stateful_partition)

Afterwards I have activated Linux (Beta) with 10GB Disk space.

I created files in the home directory in Linux.

If I open the file manager in Chromium OS and try to get access to the home directory in Linux I get the following error message: error mounting crostini container 20

Furthermore in the actual release I cannot read/write external devices (SD-Card stick). I get an error message: cannot read file system

**Comment by fydeos-alpha** [comment]
fixed, try r92-r2 release
