### ISSUE TITLE
not enough power warning intermittently on r92 (lightning bolt) 

### ISSUE THREAD

**Issue by butbutx** [FydeOS/chromium_os-raspberry_pi#187]
Raspberry Pi 4B with 8GB RAM. 32GB sd card. 

when use Chromium OS r86-2 even set to overclock 2000Mhz,  everything work fine, 
after update to r92
same pi same sd card same power supply....

but it allway show the lightning bolt on right top corner. ( not enough power warning)
i try it on default setting/ overclock setting/  system on diff. sd card/ system on usb flash drive....
all getthis not enough power warning showing intermittently.

thx all

**Comment by fydeos-alpha** [comment]
Closed per [TL:DR;](https://github.com/FydeOS/chromium_os-raspberry_pi)

> You are asking about issues about a 3rd-party app, a non-standard peripheral device or a special setup that does not benefit the general community
