### ISSUE TITLE
Can't enable "Restrict sign-in to the following users" 

### ISSUE THREAD

**Issue by dudfunk** [FydeOS/chromium_os-raspberry_pi#189]
I am on chromiumos_test_image_r83r1-rpi3b.  I signed into Chrome using a google account I made for kiosks.  I went to ChromeOS>People>Manage Other People and tried to enable Restrict sign-in to the following users but the button won't stay enabled.  It keeps going back to disable as soon as I click it.  I need to remove the "Add other user" button from the login screen to force users to Browse as Guest.

**Comment by fydeos-alpha** [comment]
try r2 release if the issue persists please reopen
