### ISSUE TITLE
Chrome Enterprise enrolment error: "Oops! The system filed to determine device model or serial number."

### ISSUE THREAD

**Issue by umalave** [FydeOS/chromium_os-raspberry_pi#190]
Raspberry Pi model 4B with 4GB RAM
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS 92.0.4515.138
 - Usb kb, touchscreen monitor via hdmi

Error: Chrome Enterprise enrollment error: "Oops! The system failed to determine device model or serial number."

**Comment by fydeos-alpha** [comment]
fixed, try r92-r2 release
