### ISSUE TITLE
Pi 3 Display Issues with HDMI to RGB adapter

### ISSUE THREAD

**Issue by ghostyroasty** [FydeOS/chromium_os-raspberry_pi#194]
**Describe the bug or issue**
When using a HDMI to rgb adapter, the initial setup display is illegible. nothing can be made out

**Describe your setup**
 - RPi 3b
 - Chromium r92r1
 - hdmi to rgb adapter

**Comment by fydeos-alpha** [comment]
Closed per [TL:DR;](https://github.com/FydeOS/chromium_os-raspberry_pi):

> You are asking about issues about a 3rd-party app, a non-standard peripheral device or a special setup that does not benefit the general community
