### ISSUE TITLE
No analog audio

### ISSUE THREAD

**Issue by thpglobal** [FydeOS/chromium_os-raspberry_pi#197]
Just downloaded the latest for my raspberry pi 4b - saw two issues: after initial boot, it walked through the login process but ended with a plain white open window. when closed, everything seemed to work except sound. I plugged in the headphones, but no audio. When clicking on the audio bar it offers 4 audio outputs - hdmi/dp, Internal Speaker (three times) - none of them seem to send sound to the headphones. (oops! solved! the second Internal speaker DOES work)

**Comment by fydeos-alpha** [comment]
The plain white open window is the "Explore" app shipped with Chromebooks. It's not relevant here with Chromium OS, we will consider removing it. Thanks
