### ISSUE TITLE
RAM usage limited, Some GUI apps don't work 

### ISSUE THREAD

**Issue by pranavr2003** [FydeOS/chromium_os-raspberry_pi#198]
First, great work on this. I tried it before, but just couldn't get GUI Linux apps to run. So props on finally fixing that (which made me install it yesterday and try it out) and it's really great so far. Planning on using it as my default OS, but I got some issues that probably need fixing. 

First, the RAM seems to be limited. I installed `neofetch` and got it to show a description, and it only gives a max of about 2.5 GB of RAM when the limit's 4 for my Pi 400.

![image](https://user-images.githubusercontent.com/56883253/144550195-124de480-463c-4490-a1a7-8d4c7586b79e.png)

You can see that on the picture above. 

Bar that, I installed `gparted` and wasn't able to get it up and running. It just kept loading infinitely on the bottom and never showed up. However, I installed it with 
```sudo apt install gparted```
on the terminal. On the other hand, I installed VSCode by dowloading the DEB file from the website. Could installing directly from the terminal be the issue here? I'm not sure about that, but I don't see how it could. 

**Describe your setup**
 - Raspberry Pi 400, 4 GB
 - Chromium OS r92 r2. Most recent image - `chromiumos_image_r92r2-rpi4b.img.xz`
 - No extra periipherals apart from the mouse

**To Reproduce**
1. Go to terminal, `sudo apt install neofetch`
2. See memory limit
3. `sudo apt install gparted`
4. Try launching it

**Expected behaviour**
Memory limit at around 4 gigs, GParted runs fine.

**Suggestion**
Just a suggestion here - Maybe you could try upgrading the linux env so all packages are up-to-date at the time of the next image release. It really took me a while to see why packages weren't installing and nothing was updating. Had to `sudo su` and try `apt update` and `apt full-upgrade` to get things running, which took a while to update. Other than that, great job on getting Linux apps to run. Looking forward to future releases

**Comment by fydeos-alpha** [comment]
Thanks for the detailed issue report.

Regarding Linux subsystem memory allocation, please note that the Linux environment that you were referring to is actually a container image under a virtual machine ([further reading](https://chromeos.dev/en/linux)). Consequently, the VM can't eat up all of the available RAM of the host system (or it would result in total annihilation and thus termination of all living species in the universe) therefore when you run `neofetch` you will observe a RAM allocation less than the available RAM of your host system which is 4GB.

Regarding particular app not running under Linux subsystem, for issues like these, it's really a case by case scenario. You could try invoking your app from the command-line and observe if there are obvious error messages on the stdout, or probe the log file and see if there are any other hints. It's usually dependency issues. This project concerns the OS itself, application issues are really out of the support scope. btw, there is not much point running `gparted` under the virtualised environment just for the record, you won't be able to modify the host system from within the Linux subsystem and it's precisely the point to set up a complicated structure to prevent malicious processes and applications from harming the host OS itself.
