### ISSUE TITLE
[Issue report] Mouse don't work while playing Sound with USB-Headphone

### ISSUE THREAD

**Issue by Mitosemensch** [FydeOS/chromium_os-raspberry_pi#199]
**Describe the bug or issue**
While connected a USB-Headphone my mouse doesn't response when playing sound.
(The error does not appear if I connect the Headphone by bluetooth.

**Describe your setup**
 - Pi 4 (4GB RAM & 32 GB storage)
 - Version 92.0.4515.183
 - Headphone: Bowers & Wilkins PX 7
 - Mouse: Logitech G502

**To Reproduce**
1. Plugin a USB-Headphone
2. Try to play Sound (e.g. Youtube or Webex, or Google Meet)

**Expected behaviour**
The cursor should freeze and no mouse input is possible.

**Comment by fydeos-alpha** [comment]
it's likely to be a power consumption issue, it eats up too much juice and thus impacts others to work. however, as the FAQ states, can't help much with non-functioning peripheral devices. We don't have the exact make/model of your USB headphone and it's almost impossible for us to reproduce the issue.
