### ISSUE TITLE
Boot partition write protected

### ISSUE THREAD

**Issue by akavkl** [FydeOS/chromium_os-raspberry_pi#20]
I'm using raspberry pi official display and it doesn't sport a HDMI port so could you uncomment it or make boot writable pls.

**Comment by akavkl** [comment]
I mean forcing HDMI output

**Comment by yunshansimon** [comment]
Mount the 12th partition on the SD card. Edit `config.txt`, insert `#` at the front of `hdmi_driver=2`.

**Comment by fydeos-alpha** [comment]
To enable read/write on the root file system, do:
```
sudo mount -o remount rw /
```
