### ISSUE TITLE
the 2nd screen is not displayed on RPI4

### ISSUE THREAD

**Issue by Stee29** [FydeOS/chromium_os-raspberry_pi#200]
Bonjour

le 2ème écran ne s'affiche pas et reste noir, alors qu'il est bien détecté (en HDMI ou en VGA)
la souris disparait sur le 2e écran et n'est pas bloquée par la fin du cadre, elle passe bien à coté

**Comment by fydeos-alpha** [comment]
in English, please

**Comment by Stee29** [comment]
Hello

the 2nd screen is not displayed and remains black, although it is correctly detected (in HDMI or VGA)
the mouse disappears on the 2nd screen and is not blocked by the end of the frame, it goes right next to it

**Comment by fydeos-alpha** [comment]
Unfortunately, we have not tested dual-monitor support with this release, yet. Consider it unsupported for now, we will take a look and may include this for the coming releases

**Comment by Stee29** [comment]
perfect thank you
