### ISSUE TITLE
[Issue report] emerge: there are no ebuilds to satisfy "~chromeos-base/chrome-icu-92.0.4515.138_rc" for /build/rpi4/.

### ISSUE THREAD

**Issue by jordanarpad** [FydeOS/chromium_os-raspberry_pi#201]
I am trying to build the latest cros release-R98-14388.B

I checkout and gsync chromium 98.0.4758.5

During build packages I hit by the error in the title.

Is it possible to build the latest R98 cros release with rpi4 overlays?

**Comment by fydeos-alpha** [comment]
yes, but you will need to manually update and satisfy `chrome-icu` package. This repo only supports r92 as of today.

**Comment by jordanarpad** [comment]
thank you for your quick response!

I have tried again with cros release-R92-13982.B and chromium-m92 but I get the same error message as in the title.
