### ISSUE TITLE
Xbox Controller and Browser games

### ISSUE THREAD

**Issue by Andrewspas** [FydeOS/chromium_os-raspberry_pi#203]
I would like to use Bluetooth Xbox Controller to play games. Unfortunately the Bluetooth don't connect correctly. Any suggestion to solve this problem? Other problem is that when I start a game in Xcloud the internet navigator show white screen with errors. If I press reload, the game works ok. I think that 64bit navigator can solve this problem. This is the best OS to play xcloud games. Good job!

**Comment by fydeos-alpha** [comment]
Apologies, can't really help issues regarding non-standard peripherals
