### ISSUE TITLE
sd issue

### ISSUE THREAD

**Issue by gameyboy11** [FydeOS/chromium_os-raspberry_pi#209]
I flashed the OS to my 32gb SD card and I can only use 2gb storage. I've tried expanding it in windows hard disk manager but it just says "invalid operation" not sure if its just something wrong with my card or if its meant to do this.
I'm using raspberry pi 4 model B. I don't have access to any disk recovery programs like Gparted. Please could you help with this.

**Comment by Jerry8538** [comment]
Check out #111

**Comment by gameyboy11** [comment]
thanks =)
