### ISSUE TITLE
How to do fast Chromium Development Workflow

### ISSUE THREAD

**Issue by Mosbeard** [FydeOS/chromium_os-raspberry_pi#214]
Hello,

how are you doing the development and testing for the chromium browser package on the rpi device?
I want to do some customizations on the chromium browser (i.e. example not showing oobe at startup, but instead the kiosk app) and need a fast workflow.
When I follow the guide from chromium os making changes to packages the suggestions don't work well. [https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_guide.md](url)

When I try "Making changes to packages whose source code is checked into Chromium OS git repositories": 
cros_workon --board=rpi4 start chromeos-base/chromeos-chrome 
building doesn't work because of:
All ebuilds that could satisfy ">=chromeos-base/chrome-icu-9999" for /build/rpi4/ have been masked.

When I try "Building an individual package":
emerge-rpi4 chromeos-base/chromeos-chrome
the whole package builds from scratch and it takes hours.

And "Making changes to the Chromium web browser on Chromium OS" [https://chromium.googlesource.com/chromiumos/docs/+/HEAD/simple_chrome_workflow.md](url)
seems to support the native boards in the source tree only and I don't know how to add support for a custom rpi board.

So I'm wondering how you guys test a little change in chromium browser source code on the rpi device without waiting for hours? What's your preferred approach for doing this?

**Comment by fydeos-alpha** [comment]
We use "simple chrome" for most chromium-only changes, including modifications/customisations for the OOBE. It does not matter which board you are working on as far as the simple-chrome is concerned. You do the browser mods, test it, you can then use the same chromium code to `emerge-rpi4 chromeos-base/chromeos-chrome` and test it on real Pi device.
