### ISSUE TITLE
[Issue report] Unable to share screen in Google Meet

### ISSUE THREAD

**Issue by woongzeyi** [FydeOS/chromium_os-raspberry_pi#216]
**Describe the bug or issue**
When trying to share screen in Google Meet, a popup showing "Your browser can't share your screen" will appear and refusing to let your share screen. 

**Describe your setup**
 - 4B with 4GB RAM
 - Chromium OS r96
 - No peripherals were connected to the board

**To Reproduce**
1. Go to 'https://meet.new'
2. Click on 'Share Screen' icon
3. Click on any choice in the popup 
4. See error "Your browser can't share your screen"

**Expected behaviour**
A screen selection window should popup, enabling you to share your screen. 

**Screenshots and/or hardware setup photos**
![image](https://user-images.githubusercontent.com/53040809/159819798-2722fc87-f313-46af-bdc0-ca2fec178b32.png)

**Comment by fydeos-alpha** [comment]
Unfortunately, this is a Google thing:
https://bugs.chromium.org/p/chromium/issues/detail?id=829916
