### ISSUE TITLE
No Audio over HDMI in release r96

### ISSUE THREAD

**Issue by KarlJoachim** [FydeOS/chromium_os-raspberry_pi#217]
I have noticed that the audio over HDMI does not work any more in the verson r96. I used/use r92r2 and there the audio over HDMI works pretty with exactly the same equipment. Did you made there a change?

I have a Raspi 4B with 4 GB a lenovo LEN L27q-30 with loudspeakers.

**Comment by netbug1010** [comment]
I am on r96-r1. All the audio output device names are the same as `Speaker(Internal)`. The audio didn't work by default, it worked when I changed output to one of them.

**Comment by KarlJoachim** [comment]
Where did you change the output? In the config.txt file?

**Comment by netbug1010** [comment]
Click on the system tray at the right bottom of screen, click on the `>` at the right of the volume bar, you will see the audio devices, change to one of them.

**Comment by KarlJoachim** [comment]
Thank you!! Problem solved.
