### ISSUE TITLE
Unable to enable the Linux Development Environment

### ISSUE THREAD

**Issue by netbug1010** [FydeOS/chromium_os-raspberry_pi#220]
**Describe the bug or issue**
When enabling, returns "Error downloading the virtualmachine, Please try again." 

**My setup**
 - Raspberry Pi 4B with 8GB RAM
 - image r96, r96-r1
 - USB thumb drive, 64G

**To Reproduce**
1. Go to 'setting'
2. Click on 'Developer', click on "Turn on"
3. Using the default setting
4. Click "Install"

**Expected behaviour**
Linux development environment is installed/enabled.

**Additional context**
I used r92 image and everything went fine on the same hardware.

**Comment by KarlJoachim** [comment]
Did yout expand the partition? See below the issue storage amount incorrect.

**Comment by netbug1010** [comment]
Yes, I have 46+G available on state partition.

**Comment by locness3** [comment]
Same issue, I have expanded the partition (if there's not enough free space, it displays an error before attemtping to download)

**Comment by netbug1010** [comment]
Just try the r102-r2 image, it is working fine with sdcard.

**Comment by locness3** [comment]
I'll have a look when possible
