### ISSUE TITLE
[Issue report] On-screen keyboard doesn't work on login screen

### ISSUE THREAD

**Issue by cletusw** [FydeOS/chromium_os-raspberry_pi#224]
**Describe the bug or issue**
On-screen keyboard doesn't work on login screen

**Describe your setup**
 - Raspberry Pi 4B with 2GB RAM
 - Chromium OS r96 r1
 - Pi connected via DSI + 5V + GND to an [official Raspberry Pi Touch Display](https://www.raspberrypi.com/products/raspberry-pi-touch-display/)
    - This required switching from KMS to FKMS in config.txt: `dtoverlay=vc4-fkms-v3d`

**To Reproduce**
1. Go to Settings > Advanced > Accessibility > Manage accessibility features > Keyboard and text input
2. Enable "Enable on-screen keyboard"
3. Sign out
4. Click the keyboard button in the bottom right corner of the screen

**Expected behaviour**
OS should show the on-screen keyboard (or at least once the password field is tapped)

**Actual behavior**
Nothing happens, even when the button is enabled and the password field is focused.

Note the on-screen keyboard shows properly in all other apps when a text field is focused or the keyboard button is tapped, just not on the login screen.

**Comment by fydeos-alpha** [comment]
This is a known limitation to Chromium OS, as the Chromium OS we released believes you are having a "Chromebox", not a Chrometablet. At this moment we do not have any intention to change this behaviour and it is thus outside the scope of this project.
