### ISSUE TITLE
Error while setting up network

### ISSUE THREAD

**Issue by p-sw** [FydeOS/chromium_os-raspberry_pi#235]
When I try to connect to network, it returns "Error configuring network".
I tried to figure out what is the problem, but it says nothing more than that.

 - Raspberry Pi 4B (RAM 8GB)
 - Chromium OS r102 r2 rpi4b
 - Power (Type C cable), Micro HDMI connected with monitor, keyboard, mouse connected.
 
![image](https://user-images.githubusercontent.com/61446372/194523775-64eba564-9825-438d-afee-2343a0e0ebb6.jpg)

**To Reproduce**
1. Turn on raspberry pi
2. Connect keyboard, mouse
3. Try to connect to a network

**Expected behaviour**
![image](https://user-images.githubusercontent.com/61446372/194523399-9b406363-5a69-41af-b941-d19d1783fafc.jpg)
That's all of this problem.
It returns that red text and keeps fail to connect to network.

**Comment by fydeos-alpha** [comment]
It seems to be wifi hotspot compatibility issues, does the wifi on your Pi work if you boot another OS?

**Comment by sserve-kr** [comment]
> It seems to be wifi hotspot compatibility issues, does the wifi on your Pi work if you boot another OS?

yes. I installed Ubuntu 22.04 with same raspberry pi, and it connected to my wifi without any problem.

**Comment by himehowareu** [comment]
I have the same problem , do you need anymore information on this issue , or is there any work arounds  as this make the rest of the OS unreachable.

**Comment by psychicgoldfish** [comment]
same issue here.

**Comment by jwaxy** [comment]
I'm having the same issue with my raspi4 is there any workaround or fixes? It became 2023

**Comment by fydeos-alpha** [comment]
@jwaxy  well, it's worth revisiting. What's the detailed spec of your Pi 4? When and where was it manufactured? A photo of it would be very helpful.

**Comment by jwaxy** [comment]
@fydeos-alpha Sure, it's a Raspberry Pi 4 Model B 2GB

![4e962697-36fb-43c4-a3cc-bce638e14aec.jpg](https://github.com/FydeOS/chromium_os-raspberry_pi/assets/98110672/649f6ab9-42a0-4442-bdd9-391e61b73486)

**Comment by maroonmoon13** [comment]
I have the same issue. I feel its a wifi country issue. I am using the pi in EU and cannot connect to wi-fi.

**Comment by sonicwind16** [comment]
I'm having the exact same issue. I was able to connect to wifi by remvoing the password requirement/encryption... Def not recommended. Do we know what WPA formats Fydos supports?

**Comment by dc-me** [comment]
Same here, wifi can only connect to open wifi.

**Comment by fydeos-alpha** [comment]
The latest release (r114) should fix this issue. Sorry guys, it's been too long, I know 🫠
