### ISSUE TITLE
Widevine not working

### ISSUE THREAD

**Issue by MegaTKC** [FydeOS/chromium_os-raspberry_pi#236]
Hi, I cannot get Spotify working on the latest r102 image. I haven't tried other images, however the latest r96 image has support for Spotify, and I was able to get it working without any issues.

**Comment by fydeos-alpha** [comment]
r108 has just been released; give it a spin. Otherwise, try [openFyde for Raspberry Pi](https://github.com/openFyde/overlay-rpi4-openfyde) instead.
