### ISSUE TITLE
[Issue report]

### ISSUE THREAD

**Issue by NyLan-1** [FydeOS/chromium_os-raspberry_pi#237]
Missing Swiss keyboard layout.
In FydeOS for Rpi4 the Swiss layout is installed.
But not in Chromium_OS for RPi4

Would be great to add it in this version of ChromiumOS.

**Comment by fydeos-alpha** [comment]
It's part of a proprietary i18n implementation (with commercial licenses rather than open source) I am afraid 🤷🏻‍♂️ not much that we can do about this at the moment
