### ISSUE TITLE
[Issue report] After cros_wrokon=rpi4 !! All ebuilds that could satisfy "~chromeos-base/chrome-icu-96.0.4664.208_rc" for /build/rpi4/ have been masked. !!! One of the following masked packages is required to complete your request: - chromeos-base/chrome-icu-96.0.4664.208_rc-r1::cros-pi (masked by: package.mask)

### ISSUE THREAD

**Issue by wwd-615** [FydeOS/chromium_os-raspberry_pi#240]
!!! All ebuilds that could satisfy "~chromeos-base/chrome-icu-96.0.4664.208_rc" for /build/rpi4/ have been masked.
!!! One of the following masked packages is required to complete your request:
- chromeos-base/chrome-icu-96.0.4664.208_rc-r1::cros-pi (masked by: package.mask)

(dependency required by "chromeos-base/chromeos-chrome-96.0.4664.208_rc-r1::cros-pi" [ebuild])
(dependency required by "virtual/chromeos-interface-1-r7::chromiumos[-chromeless_tty]" [ebuild])
(dependency required by "virtual/target-chromium-os-1-r185::chromiumos" [ebuild])
(dependency required by "virtual/target-os-1-r5::chromiumos" [ebuild])
(dependency required by "virtual/target-os" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
13:11:59 ERROR   : emerge detected broken ebuilds. See error message above.
(cr) (release-R96-14268.B/(f993911...)) ubuntu@ubuntu-VirtualBox ~/chromiumos/src/scripts $ emerge --info 
Portage 2.3.75 (python 3.6.12-final-0, !/usr/local/portage/chromiumos/profiles/default/linux/amd64/10.0/sdk, gcc-10.2.0, glibc-2.32-r16, 5.19.0-35-generic x86_64)
=================================================================
System uname: Linux-5.19.0-35-generic-x86_64-11th_Gen_Intel-R-_Core-TM-_i5-1135G7_@_2.40GHz-with-glibc2.2.5
KiB Mem:     4017172 total,    621972 free
KiB Swap:    3991548 total,   3022116 free
sh bash 4.4_p23-r1
ld GNU ld (GNU Binutils) 2.36.1
ccache version 3.7.7 [disabled]
app-shells/bash:          4.4_p23-r1::portage-stable
dev-java/java-config:     2.2.0-r4::portage-stable
dev-lang/python:          2.7.15-r9::chromiumos, 3.6.12-r5::chromiumos
dev-util/ccache:          3.7.7::portage-stable
dev-util/cmake:           3.20.5::portage-stable
dev-util/pkgconfig:       0.29.2::portage-stable
sys-apps/baselayout:      2.2-r1::chromiumos
sys-apps/sandbox:         2.11-r9::chromiumos
sys-devel/autoconf:       2.69::portage-stable
sys-devel/automake:       1.10.3-r1::portage-stable, 1.11.6-r1::portage-stable, 1.15.1-r2::portage-stable
sys-devel/binutils:       2.36.1-r2::chromiumos
sys-devel/gcc:            10.2.0-r22::chromiumos
sys-devel/gcc-config:     2.3.2-r1::portage-stable
sys-devel/libtool:        2.4.6-r6::chromiumos
sys-devel/make:           4.2.1-r4::portage-stable
sys-kernel/linux-headers: 4.14-r39::chromiumos (virtual/os-headers)
sys-libs/glibc:           2.32-r16::chromiumos
Repositories:

**Expected behaviour**

**Screenshots and/or hardware setup photos**
If applicable, add screenshots to help explain your problem. If your problem is hardware related, it's much easier to include a photo of how your setup looks like.

**Additional context**

**Comment by fydeos-alpha** [comment]
You need to fix the write-up and presentation of this build error, and provide more information regarding how you came this far to re-open this issue.
