### ISSUE TITLE
black screen when opening Play Store

### ISSUE THREAD

**Issue by Lolothepro** [FydeOS/chromium_os-raspberry_pi#244]
**Describe the bug or issue**
I get a black screen when I open the play store

**Describe your setup**
 - Raspberry PI 4 8Go
 - FydeOS v16.0 SP 1

**To Reproduce**
1. Launch the Play Store
2. A black screen appeared

**Expected behaviour**
Launch of the Play Store

**Screenshots and/or hardware setup photos**

![Screenshot 2023-04-15 18 49 31](https://user-images.githubusercontent.com/68275908/232238988-29a2b3b5-4ada-471c-857f-8916b1f686d0.png)

**Comment by fydeos-alpha** [comment]
This is FydeOS, not Chromium OS for Raspberry Pi which this repo is about. To get help on FydeOS, try [Telegram](https://t.me/hi_fydeos), [Discord](https://discord.gg/Qv3kxGeMJQ) or [Community](https://community.fydeos.io/). 

ps. there will be a significant update on FydeOS for Raspberry Pi dropping this month, stay tuned.
