### ISSUE TITLE
How to use drc or eq audio processing algorithm

### ISSUE THREAD

**Issue by wwd-615** [FydeOS/chromium_os-raspberry_pi#248]
I want to use drc in ChromiumOS for audio processing, but by printing, only the sink algorithm runs.
How to configure and use drc?
Can you give me a hand? Thank you very much

**Comment by fydeos-alpha** [comment]
This is not an issue under the scope of this project, if you have questions regarding Chromium OS itself, please refer to the Chromium Authors

**Comment by wwd-615** [comment]
sorry, it's not that I have questions about ChromiumOS. 
It's that I haven't found the dsp.ini for rpi4, so I don't know how to configure drc for ChromiumOS audio running on Raspberry PI.
