### ISSUE TITLE
[Issue report] Removing the OS from my sdcard

### ISSUE THREAD

**Issue by SSP6904** [FydeOS/chromium_os-raspberry_pi#249]
**Describe the bug or issue**
I was going to remove the OS from the SD card, but attempts to do so causes the partition table to revert the changes unexpectedly, including the use of erasing and/or formatting some partitions. I also noticed that when using the OS and doing changes on their makes it revert and clear my progress, even using powerwash to format it as well..

**Describe your setup**
 - Raspberry Pi 4B 8GB
 - chromiumos image r89r1
 - Keyboard and mouse

**To Reproduce**
Not able to do

**Expected behaviour**
I expected the drive to erase it.

**Screenshots and/or hardware setup photos**
![2023-06-26 17-09-40](https://github.com/FydeOS/chromium_os-raspberry_pi/assets/75172901/284f1355-ac64-4487-a790-95bf77e488e2)

**Comment by Damenly** [comment]
Sorry I am not a fan of GUI gparted. You can try commmd line:

1. `sudo fdisk /dev/sda`
2. Press key `g`  and confirm 
3. Press key w 
4. `lsblk`

**Comment by SSP6904** [comment]
Didn't work, same thing

**Comment by Damenly** [comment]
Please paste all outout or screen record.

**Comment by SSP6904** [comment]
![2023-06-26 21-11-39](https://github.com/FydeOS/chromium_os-raspberry_pi/assets/75172901/2f3735c4-b105-49aa-af78-2e9bb48f3af3)

I did what you told me to type, but the partitions came back, also on every reboot.

**Comment by Damenly** [comment]
The fdisk reported that your SD card was mounted.

0. lsblk
1. sudo umount /dev/sda*
2.sudo fdisk /dev/sda
3. Press key `g` and confirm using key `enter`
4. Press key w
5. lsblk

**Comment by SSP6904** [comment]
That also did not work. I haven't responded in a while so I can't fully remember part of this issue.
