### ISSUE TITLE
Bluetooth controller issues.

### ISSUE THREAD

**Issue by MuTong233** [FydeOS/chromium_os-raspberry_pi#25]
On the first boot,bluetooth could be turned on.But I didn't try to connect to any device.And then my bluetooth couldn't turn on.After several reboot,it suddenly can be turned on.But it can't connect to any device.
Here is dmesg message
[   51.503124] Bluetooth: Core ver 2.22
[   51.511538] Bluetooth: HCI device and connection manager initialized
[   51.518079] Bluetooth: HCI socket layer initialized
[   51.523152] Bluetooth: L2CAP socket layer initialized
[   51.528400] Bluetooth: SCO socket layer initialized
[   51.862617] Bluetooth: HCI UART driver ver 2.3
[   51.867180] Bluetooth: HCI UART protocol H4 registered
[   51.872508] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   51.879215] Bluetooth: HCI UART protocol Broadcom registered
[   52.004672] Bluetooth: hci0: BCM: chip id 107
[   52.021002] Bluetooth: hci0: BCM: features 0x2f
[   52.048788] Bluetooth: hci0: BCM4345C0
[   52.052800] Bluetooth: hci0: BCM (003.001.025) build 0000
[   52.058429] bluetooth hci0: Direct firmware load for brcm/BCM.hcd failed with error -2
[   52.066583] Bluetooth: hci0: BCM: Patch brcm/BCM.hcd not found
[   53.035799] Bluetooth: RFCOMM TTY layer initialized
[   53.040870] Bluetooth: RFCOMM socket layer initialized
[   53.046226] Bluetooth: RFCOMM ver 1.11
[ 1619.272684] Modules linked in: aes_neon_blk rfcomm crypto_simd cryptd aes_arm64 i2c_dev uinput iptable_raw hci_uart xt_CT btbcm lzo serdev lzo_compress lzo_decompress bluetooth zram nfnetlink fuse ecdh_generic crc32_ce i2c_bcm2835 sdhci_iproc uio_pdrv_genirq uio nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_filter ip6_tables xt_tcpudp ipv6 nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack iptable_filter ip_tables x_tables lan78xx brcmfmac brcmutil cfg80211 rfkill dm_crypt dm_mod evdev joydev dax quota_v2 quota_tree
[ 2566.176587] Modules linked in: hid_multitouch aes_neon_blk rfcomm crypto_simd cryptd aes_arm64 i2c_dev uinput iptable_raw hci_uart xt_CT btbcm lzo serdev lzo_compress lzo_decompress bluetooth zram nfnetlink fuse ecdh_generic crc32_ce i2c_bcm2835 sdhci_iproc uio_pdrv_genirq uio nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_filter ip6_tables xt_tcpudp ipv6 nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack iptable_filter ip_tables x_tables lan78xx brcmfmac brcmutil cfg80211 rfkill dm_crypt dm_mod evdev joydev dax quota_v2 quota_tree

**Comment by yunshansimon** [comment]
Did your bluetooth work with raspbian?
