### ISSUE TITLE
[Issue report]New Browser Installation

### ISSUE THREAD

**Issue by Ex-pi-rimental** [FydeOS/chromium_os-raspberry_pi#258]
**Describe the bug or issue**
If I install new browsers using linux they appear glitchy and most of the times a black screen apeears.

**Describe your setup**
 - Raspberry PI 400 4GB RAM
 - FydeOS latest Version
 - Default Setup

[Screen recording 2024-06-09 02.05.09.webm](https://github.com/FydeOS/chromium_os-raspberry_pi/assets/170480393/4706274c-f636-49c6-99fa-3f242a39597e)

**Comment by Lorde627** [comment]
On ChromiumOS, the only recommended browser to use is Chromium.

**Comment by Ex-pi-rimental** [comment]
well i am unable to understand why the other applications flicker?
