### ISSUE TITLE
HDMI audio not working after command

### ISSUE THREAD

**Issue by Piflyer** [FydeOS/chromium_os-raspberry_pi#41]
So I followed issue #17, but I still can't force audio via HDMI on my Raspberry Pi 4 on the latest release. Is there a way that I can replace the current file with the default one?

**Comment by yunshansimon** [comment]
First, make sure your HDMI audio is working with raspbian.  Then, modify the file `/etc/init/force_audio_output_to_headphones.conf` . If `2` doesn't work, change it to `0`.

**Comment by sgtram** [comment]
Hi, whatever I set 2 or 0 the sound always headphones. No HDMI audio. Any idea?

**Comment by Dittizardichu** [comment]
I cannot edit the force audio output file from within Chromium OS. It says the file is unwritable, even with root privileges.

**Comment by Fusion3Design** [comment]
i do not even see this file if I look in /etc/init on the latest build

**Comment by rimonmath** [comment]
> i do not even see this file if I look in /etc/init on the latest build

I also don't see this file
