### ISSUE TITLE
Touchscreen Inverse X

### ISSUE THREAD

**Issue by pt4si3k83** [FydeOS/chromium_os-raspberry_pi#49]
Hi,
I successfully installed the latest build on Rpi4 and I'm using 22inches LCD monitor with USB touchscreen. Touchscreen is being detected by system as 'XDTouch IrTouchScreen' . Everything works fine BUT its X axis is inverted. I spent alot of time trying to do so, but I don't know "freon" at all. 

If there was an XOrg then adding the following part to 'xorg.conf' would do the trick:
`Section "InputDevice"`
`   Identifier "touchscreen"`
`   Driver "evdev"`
`   (...)`
`   Option "InvertX" "True"`
`EndSection`

 Is there any chance to configure it?

**Comment by yunshansimon** [comment]
The input device configuration files are at `/etc/gesture`.

**Comment by pt4si3k83** [comment]
Than you @yunshansimon . I'm trying to configure it in the same way (or similar) I did on Raspbian, but it seems to not working at all. Can you tell me where can I find UI logs so that I could see whether my configuration is being read at all? Is there any log file - like 'xorg.log' ?

**Comment by yunshansimon** [comment]
`/var/log/ui/ui.*` :  graphic related logs. 
`/var/log/chrome/chrome` : chrome main logs.
`evtest` : the command for testing input device.

**Comment by pt4si3k83** [comment]
Hey, I tried to modify one of the file which is already in `/etc/gestures`. I tried to create a new one there with my configuration. Unfortunatelly there were no change in the system nor any information in any log file. 

Are the `/etc/gestures/*.conf` files being used at all?

**Comment by pt4si3k83** [comment]
Is there any way to recompile the kernel module (usbtouchscreen.c) on my RPi4 to add a support for "InvertX" parameter? I was searching for this over the internet but I didn't find any useful information (instructions).

**Comment by pt4si3k83** [comment]
I managed to rebuild `usbtouchscreen` kernel module to support `invert_x` parameter and now it works fine. My issue with X axis seems to be solved.

However I think there still might be something wrong with `/etc/gestures/*.conf` files support.
