### ISSUE TITLE
Timezone Resets on Reboot

### ISSUE THREAD

**Issue by IanKnighton** [FydeOS/chromium_os-raspberry_pi#52]
**Describe the bug or issue**
I've set the Raspberry Pi up as a Kiosk to display our dashboard from Uptime Robot. On launch, I see a screen that says "Clock is behind" and no pages with SSL will load. 

I've found that I can go into the command line and run `sudo date -s "Wed Jan 22 20:59:00 UTC 2020"` and then refresh the page, but that isn't really tenable for a standalone kiosk. 

I haven't found a way to set this and have it persist after reboot. 

I've also found that, even as root, I am unable to edit the `/etc/chrome_dev.conf` file to turn off kiosk mode and try to set this through the Chrome OS. 

**Describe your setup**
- Raspberry Pi 3b
- Connected via HDMI to a TV

**To Reproduce**
Launch into Kiosk Mode with a page using SSL

**Expected behaviour**
The timezone should be able to be set and persisted across reboots.

**Comment by IanKnighton** [comment]
So I've tried to change the `/etc/localtime' link to make sure it's in my timezone. I'm running into another error that says it's a readonly filesystem. 

```
chronos@localhost ~ $ sudo ln -sf /usr/share/zoneinfo/America/Boise /etc/localtime 
ln: cannot remove '/etc/localtime': Read-only file system
```

Did I do something wrong when I flashed the SD card?

**Comment by fydeos-alpha** [comment]
To modify rootfs you will need to issue this command first:
```
sudo mount -o remount rw /
```

We are still investigating the time issue.

**Comment by josedelinux** [comment]
![IMG_20200202_183102](https://user-images.githubusercontent.com/37724086/73607264-d7023300-45ee-11ea-9d73-414a15f19072.jpg)
same issues .
I also noticed that it tried to access a website( periodex.co ) about periodic table of elements,is it a test of connection? 
by the way ,how to open terminal? , I tried both `ctrl`+`alt`+`T` and `ctrl`+`alt`+`f2`, not working

**Comment by yunshansimon** [comment]
try:

```bash
$ sudo mount -o remount rw /
$ sudo sh -c 'echo start on started boot-services > /etc/init/system-services.override'
$ sudo reboot
```

**Comment by fydeos-alpha** [comment]
resolved in r80 release, closing.
