### ISSUE TITLE
[Request] [Not a bug] Support for other ARM64 devices (eg. Galaxy Book2, Surface Pro X)

### ISSUE THREAD

**Issue by chrispilot2293** [FydeOS/chromium_os-raspberry_pi#54]
*NOT A BUG, REQUEST FOR DEVICE SUPPORT*
Chromium would be much more useful than Windows on these devices, but building it is vastly beyond my knowledge.

Could support for other ARM64 laptops/tablets such as my Galaxy Book2, the new Surface Pro X and other Windows 10 ARM devices be something y'all could get going? 

Id be happy to provide and help or device access (Book2) that would be needed to get it going stable!

Thanks!

**Describe your setup**
 - Your Raspberry Pi model and spec variant, e.g. 4B with 2GB RAM
 - Your Chromium OS for Raspberry Pi release version, e.g. Chromium OS r77 r3
 - Your hardware configuration and setup, e.g. how you have wired the Pi board with any other peripheral connected to it

**To Reproduce**

**Expected behaviour**

**Screenshots and/or hardware setup photos**
If applicable, add screenshots to help explain your problem. If your problem is hardware related, it's much easier to include a photo of how your setup looks like.

**Additional context**

**Comment by fydeos-alpha** [comment]
Hi, thanks for your interests and support. Porting Chromium OS for commercial ARM devices (as opposed to development/DIY/open-source hardware like Raspberry Pi) requires a lot more dependencies and support from various vendors which in reality are impossible to acquire. The firmware and OS bootstrapping are also vastly different in the ARM realm than with x86, maintaining releases for each and every device without commercial interest are unrealistic. 

This project only focuses on Raspberry Pi. Hence issue closed.
