### ISSUE TITLE
Use all SD memory

### ISSUE THREAD

**Issue by bronco401** [FydeOS/chromium_os-raspberry_pi#63]
Sorry, this is probably a dumb question, but when I get everything setup on my SD card and run it on my Pi, is states there are only a few MB free.  How to I reallocate the unused space on the SD card so FydeOS can use it?

The OS launches fine, but I can't get my profile to download as it runs out of memory.

3B with 32gb SD - I've very new to the Pi and I'm trying to setup a chrome desktop for my kids for school now that their home.

**Comment by markwhi** [comment]
Take a look at Issue #10 for the fix.

**Comment by bronco401** [comment]
I still don't get how to access the terminal?  Sorry I'm a newbie.

**Comment by fydeos-alpha** [comment]
Enter tty shell by hitting ctrl + alt + F2, log in with username `chronos`, password `test0000`

**Comment by yetipi3** [comment]
ill be honest i don't understand very much either, any help would be great

**Comment by Jerry8538** [comment]
@fydeos-alpha @bronco401 ctrl + alt + t works too. If your problem is solved, you can close this issue.
