### ISSUE TITLE
Raspberry Pi Touchscreen

### ISSUE THREAD

**Issue by soledger39** [FydeOS/chromium_os-raspberry_pi#64]
Can you help me I'm trying to get Chromium OS working on Raspberry Pi Touch Screen.

I have it working great via the HDMI connection but really want to use the touch screen.

Many thanks for help

Gareth

**Comment by fydeos-alpha** [comment]
It's a known graphics glitch with Pi and a workaround has been proposed in an earlier issue:

https://github.com/FydeOS/chromium_os-raspberry_pi/issues/16#issuecomment-576212327
