### ISSUE TITLE
How to enable developer mode for running Android apps

### ISSUE THREAD

**Issue by Dagjoh** [FydeOS/chromium_os-raspberry_pi#68]
I want to enable developer mode so that I could open up for Android apps on the Raspberry Pi 3+ when running Chromium OS. This is done by getting the system in recovery mode first. 

How is this done?

**Comment by Eiarzate1** [comment]
I am also interested in this topic. Any updates?

**Comment by fydeos-alpha** [comment]
Android subsystem support is not part of Chromium OS, therefore it's out of scope for this project.

By the way, it's definitely not as simple as "put the system in recovery mode" and then "enable developer mode", those terms only apply to Chrome devices, Pi is not a Chrome device.
