### ISSUE TITLE
Unable to disable guest browsing

### ISSUE THREAD

**Issue by dawithers** [FydeOS/chromium_os-raspberry_pi#70]
**Describe your setup**
 - 4B 4GB
 - r80 release

**To Reproduce**
1. Open settings
2. Select "You and Google" on the left
3. Click "Manage other people"
4. Try to toggle "Enable Guest browsing"

It flickers back and forth but ultimately lands on the enabled setting

**Comment by fydeos-alpha** [comment]
fixed and tested working in r86 releases.
