### ISSUE TITLE
Admin not actually admin...

### ISSUE THREAD

**Issue by Blite33** [FydeOS/chromium_os-raspberry_pi#71]
**Describe the bug or issue**
This bug is a bug that will not allow me administrator in order to connect to my phone. (This may not be a FydeOS bug, but i'd like to know what's going on, and my google account isn't broken)(Maybe i should use the prompt and sudo for this)

**Describe your setup**
 - Raspberry pi 3B+, which usually displays low power, but doesn't in FydeOS.
 - Chromium 80. (Latest edition of FydeOS, as of 14th of May 2020)
 - No special hardware config. OS flashed with BalenaEtcher.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Connect to phone'
3. There, an icon appears saying you need district admin access to do this. It also gives a link for troubleshooting, but it only talks about the google account.

**Expected behaviour**
The switch should not be greyed out, and I should be able to turn the switch on, and setup the connection to my phone.

This was the only OS i could get working on my pi with the low voltage warning coming on during setup. I have not tried the official brick, because I'm broke and can't pay for one. I am using a gold contact 1ft usb cable, and a 15w 2A black fast charger from samsung.

**Comment by fydeos-alpha** [comment]
It's not FydeOS, it's Chromium OS, first of all.

My guess that feature isn't included in Chromium OS, so much like Google assistant, unfortunately.
