### ISSUE TITLE
Chromium Outdated

### ISSUE THREAD

**Issue by SrIzan10** [FydeOS/chromium_os-raspberry_pi#74]
I have a problem with Chromium. It's outdated. I can't play Spotify music because of the outdated Chromium.

 - Raspberry Pi 3B+ with 1GB RAM
 - Release version: Chromium OS 80.0.3987.158 (I am new in the system, so I don't know where search it)
 - I have the Pi board connected to my Router, and the Spanish (Spain) version of Chromium OS becouse I am spanish

**To Reproduce**
1. Go to the Spotify App
2. Put some music
![IMG_0429](https://user-images.githubusercontent.com/66965250/84687909-4d933380-aef3-11ea-9eb4-58bcc19bb883.JPG)

4. See error: 
 ![IMG_0428](https://user-images.githubusercontent.com/66965250/84687904-49ffac80-aef3-11ea-83eb-d5947263d146.JPG)
                               **An error has occurred**
Spotify is no longer compatible with this version of Chrome. Update the browser to listen without interruption.

**Expected behaviour**
Put the music normal

**Comment by fydeos-alpha** [comment]
could you please retry this on the r83 release, we have tested spotify and it worked fine

**Comment by FiodorTretyakov** [comment]
Does it mean the widevine DRM work on r83?

**Comment by SrIzan10** [comment]
Oh, sorry for no responding... I am going to try it right now.

**Comment by YuriFontella** [comment]
I have a similar problem in the r86r2-rpi4b version. I don't know if it can be related to widevine. Can this ever work?

![image](https://user-images.githubusercontent.com/4920619/108439354-de16d600-722f-11eb-880b-d853b016dcef.png)

_"It looks like your browser is no longer compatible with netflix. Install the latest version or try a different browser."_

**Comment by SrIzan10** [comment]
Sorry for the no response, now it works.

**Comment by SrIzan10** [comment]
> I have a similar problem in the r86r2-rpi4b version. I don't know if it can be related to widevine. Can this ever work?
> 
> ![image](https://user-images.githubusercontent.com/4920619/108439354-de16d600-722f-11eb-880b-d853b016dcef.png)
> 
> _"It looks like your browser is no longer compatible with Netflix. Install the latest version or try a different browser."_

This issue had been closed @YuriFontella . Try making another issue.
