### ISSUE TITLE
would like to run docker in this

### ISSUE THREAD

**Issue by rhildred** [FydeOS/chromium_os-raspberry_pi#76]
I tried to run docker in this image on my Raspberry Pi 3 model b with 1gb of ram. These are the steps that I went through.

1. `sudo mount -o remount,rw /`
2. downloaded [docker stable binaries](https://download.docker.com/linux/static/stable/armhf/docker-18.09.9.tgz)
3. `sudo mkdir -p /opt/bin`
4. `sudo groupadd docker`
5. `sudo usermod -aG docker $USER`
6. Untarred docker-18.09.9.tgz and copied the binaries to /opt/bin
7. `sudo dockerd`
8. Opened another terminal and ran `docker ps` With the following results:
```
chronos@localhost / $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
chronos@localhost / $ 
```
9. Ran `docker run hello-world` with the following results:
```
chronos@localhost / $ docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory\"": unknown.
ERRO[0006] error waiting for container: context canceled 
chronos@localhost / $ 
```
10. I am not too surprised because I had some complaints when I ran `docker info`
```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 1
Server Version: 18.09.9
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 5.4.22-v7-g894dece01-dirty
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 679.4MiB
Name: localhost
ID: 3E2H:H7ET:AYRX:MKMZ:6NTA:HNFS:FSBB:E2MJ:HHWZ:L4SY:YXNF:NYA3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpuset support
```
From these error and [this article](https://github.com/moby/moby/issues/1863) I am hoping that there will be some kernel options that can be used to make the above steps work. Even better would be to have docker pre-installed in the image.
I am using the 1gb Raspberry Pi 3 model B for testing because I had one already. I need to be able to finally run this on an 8gb Rasberry PI 4.

**Comment by fydeos-alpha** [comment]
You can now test your idea with Linux(beta) in r86r1 build, ideally with your 8GB Pi4B
