### ISSUE TITLE
I can't open terminal on RPi 4B.

### ISSUE THREAD

**Issue by Pktro** [FydeOS/chromium_os-raspberry_pi#79]
Hello! I have a problem with FydeOS. I have a Raspberry Pi 4B with 4GB of RAM and Chromium 80.0.3987.163. I want to open the terminal because I have a problem with the SD card, that only detects 260 MB of free space when I'm using an SD card of 64GB that only haves the system data. I have searched how to solve the problem on FydeOS's GitHub page and I found that I have to open the terminal, and replace one .txt of the system, but when I try to access to the terminal pressing the keys "Ctrl+Alt+F2", my RPi stops showing image. I don't know why this is happening, but if If it helps to try to solve the problem, I also had another problem with my RPi 4. When I bought it, I installed FydeOS as my default OS (that is, I installed FydeOS as "the first OS of my RPi", which I only installed FydeOS, I didn't install any other OS on that RPi before). I connected the RPi to the power and my monitor, and even being the official accessories, my RPi gave no image signal. Searching, again, on the official GitHub page of FydeOS, I found that it was a compatibility problem between the resolution of my monitor and my RPi. I modified the file "config.txt" and now it works correctly. Of accessories for my RPi, I have the official keyboard and mouse, an HDMI switch, since I also have my Nintendo Switch connected to the monitor, and a small fan for my RPi connected to the 3.3V and GND stations of my RPi. Occasionally, I also plug my Razer Kraken Pro V2 headphones into my RPi's 3.5mm Mini Jack port. I think that the latter does not have much to do with the problem, but I put it in case it was related to this and I did not know it, it is that I am a little novice. And finally, I don't know if it will be noticed, but sorry for using Google Translate. I am Spanish and I only know a little English. Thanks for the help!

**Comment by yunshansimon** [comment]
First of all, there is no OS like FydeOS for rpi4. It's just ChromiumOS for RPI which based on the official raspberry kernel and ChromiumOS sources. "Ctrl+Alt+F2" is never working because of the graphic driver issue, you can use "Ctrl + Alt +T" instead which has to run after login. The hotkey will open a browser tab for a command console, then type 'shell'. For most hardware related issues, you can find the answer on the official site of the raspberry pi.
