### ISSUE TITLE
chromium OS not using all 64GB 

### ISSUE THREAD

**Issue by yetipi3** [FydeOS/chromium_os-raspberry_pi#80]
so i've seen one other post like this but its closed and i don't know how to fix this even the solution didn't make much sense to me (i'm new to this)

**Comment by nmcain** [comment]
You need to execute the script for expanding the space.

**Comment by yetipi3** [comment]
How though unfortunately i don't understand.

**Comment by fydeos-alpha** [comment]
check out this "resolved with answer" issue:
https://github.com/FydeOS/chromium_os-raspberry_pi/issues/10
