### ISSUE TITLE
R83 RPi3B+ RPi 7" touchscreen touch not working

### ISSUE THREAD

**Issue by zan73** [FydeOS/chromium_os-raspberry_pi#81]
Genuine RPi 7" touchscreen not detecting touches

RPi3B+
Chromium OS r83
Modified config.txt to enable 7" touchscreen display output (sourced details from a closed issue)

**To Reproduce**
1. Touch screen on wifi network selection screen, nothing happens

**Expected behaviour**
1. Touch screen on wifi network selection screen, selection registered and able to touch next button to continue

Earlier version (r77 r3) seems to work fine

**Comment by fydeos-alpha** [comment]
The official screen enforces fkms mode, hence the previous need to modify config.txt. The current r86r1 build fixed this issue.
