### ISSUE TITLE
No HDMI output

### ISSUE THREAD

**Issue by jfgarciamex** [FydeOS/chromium_os-raspberry_pi#82]
Hi, just trying FydeOS on a Raspberry pi 4, but I can not make my display to work. I tried editing config.txt file and adding hdmi_safe=1 and hdmi_mode=16, to no avail. I have not problems with Raspberry OS, Ubuntu and even Android 10. My monitor is 2K, so I'm guessing that may be the problem, but could not find a way to make it work. Any suggestion is welcomed. Thanks!

**Comment by LCCR193** [comment]
My pi 3B+ has display working but at the setup the screen is a total mess, distorted more than anything, I can click things, and stuff changes, but no way of knowing what is on the screen....(latest build)

**Comment by fydeos-alpha** [comment]
dup #109
