### ISSUE TITLE
[Issue report] Flickering hdmi output; cursor distorted

### ISSUE THREAD

**Issue by Larhanya** [FydeOS/chromium_os-raspberry_pi#84]
**Describe the bug or issue**
Even after logging in to Chromium, the video output to my HDMI monitor flickers, especially when mousing or interacting with the UI. The cursor spends most of its time as a pixelated box of colours. Sometimes half the screen becomes a pixelated mess of colours (graphical noise).

**Describe your setup**
Raspberry Pi 4B with 8GB RAM
Chromium OS release-R83-13020.B
Ethernet connection; HDMI output; Logitech K400 Plus wireless keyboard; Labists starter kit fan, heatsinks, and case; SanDisk extreme 128GB SD card

**To Reproduce**
1. Start up the Pi
2. Move mouse
3. Cringe

**Expected behaviour**
No graphic flickering; clear cursor; no distortion or graphical artefacts or noise

**Additional context**
In the "About Chromium" page in settings it is telling me that it is a 32-bit version of Chromium. That seems...wrong...

**Comment by fydeos-alpha** [comment]
It is 32-bit version of Chromium, but the kernel is of 64-bit. In r86r1 build, we've done quite some graphics related optimisations and glitches as you've mentioned should be improved by a great deal.
