### ISSUE TITLE
Chrome OS build for aarch64 Amlogic S905, RK SoC (Android TV boxes) 

### ISSUE THREAD

**Issue by siliconhippy** [FydeOS/chromium_os-raspberry_pi#89]
Hi 😊 there,

Great job:
https://www.google.com/amp/s/www.makeuseof.com/tag/use-chrome-os-raspberry-pi/amp/

Title says all, but is there a way to use FydeOS, given its stated optimizations in read.me, to build for aarch64 Android TV boxes ( Amlogic S905/ x/w or Rockchip RK 3229+)

Both above SoCs have Debian based armbian.com Linux builds.

**Comment by fydeos-alpha** [comment]
There is no way to use any existing FydeOS release on ARM devices. 

Porting Chromium OS to a new hardware platform (especially ARM) is not an easy undertaking, unfortunately, we don't have plans to support new ARM set-top boxes unless under commercial capacity.

This repo only concerns Chromium OS on Raspberry Pi.
