### ISSUE TITLE
sudo default password?

### ISSUE THREAD

**Issue by HansLanger** [FydeOS/chromium_os-raspberry_pi#9]
Hi, 
What is the default SUDO password?

I came through this link: https://www.raspberrypi.org/forums/viewtopic.php?t=227281
I downloaded the bin, with etcher, I wrote the bin into an SD, I started my raspi3b+ with the SD, and its immediately started chrome os, great work! thank you!.
Then,I open the terminal, I shell, and when I write "sudo command" and it ask me for a password. I can't do anything that I need without sudo privileges.

Thanks.

**Comment by HansLanger** [comment]
Nevermind, the password was right there. I let this post in case someone has the same issue:
password: test0000

**Comment by xNUTs** [comment]
Use Terminal sudo -s 
Enter PASSWD to create a password.
