### ISSUE TITLE
How to install google play store or APKs in ChromiumOS for rpi4

### ISSUE THREAD

**Issue by ibrunops** [FydeOS/chromium_os-raspberry_pi#90]
Hi! I would like to know if it is possible to install APKs or google play store in ChromiumOS for rp4 as it can in chromeOS for example. Thanks.

**Comment by jordanwilliams1** [comment]
While this is open I'd like to know too if possible, lol. I Have a rp3

**Comment by fydeos-alpha** [comment]
it won't be possible with Chromium OS (the open-source version) unless the Chromium Authors decided to change the status quo. Sorry guys. There is a chance with FydeOS if we can resolve some of the key performance issues, but not at the moment.
