### ISSUE TITLE
Building comilation failing : ERROR: sys-kernel/upstream-kernel-mainline-5.4.21-r2::chipset-bcm2837 failed

### ISSUE THREAD

**Issue by vikaspac** [FydeOS/chromium_os-raspberry_pi#91]
Hi FydeOS,

I am trying to compile for raspberry pi3 for first time.
Got below failure during the below command:

#./build_packages --board=rpi3 --nowithautotest 

Please help on this.

Chromium OS version information:
    CHROME_BASE=
    CHROME_BRANCH=80
    CHROME_VERSION=
    CHROMEOS_BUILD=12739
    CHROMEOS_BRANCH=124
    CHROMEOS_PATCH=2020_09_01_2021
    CHROMEOS_VERSION_STRING=12739.124.2020_09_01_2021
.................................................................................................................................
>>> 20:46:58 Emerging binary (575 of 883) media-sound/cras-sys-0.1.0-r12::chromiumos for /build/rpi3/
>>> 20:46:59 Failed to emerge sys-kernel/upstream-kernel-mainline-5.4.21-r2 for /build/rpi3/, Log file:
>>> 20:46:59   /build/rpi3/tmp/portage/logs/sys-kernel:upstream-kernel-mainline-5.4.21-r2:20200901-151628.log
>>> 20:46:59 === Start output for job upstream-kernel-mainline-5.4.21-r2 ===
upstream-kernel-mainline-5.4.21-r2:  * Package:    sys-kernel/upstream-kernel-mainline-5.4.21-r2
................................................................................................................................
 * ERROR: sys-kernel/upstream-kernel-mainline-5.4.21-r2::chipset-bcm2837 failed (unpack phase):
 *   git-2_update_repo: can't update from https://github.com/raspberrypi/linux.git
 * 
 * Call stack:
 *               ebuild.sh, line  125:  Called src_unpack
 *             environment, line 5122:  Called cros-kernel2_src_unpack
 *             environment, line 1969:  Called cros-workon_src_unpack
 *             environment, line 2239:  Called git-2_src_unpack
 *             environment, line 3940:  Called git-2_fetch
 *             environment, line 3757:  Called git-2_update_repo
 *             environment, line 3998:  Called die
 * The specific snippet of code:
 *       [[ -n ${EGIT_REPO_URI_SELECTED} ]] || die "${FUNCNAME}: can't update from ${EGIT_REPO_URI}"
 * 
 * Build log: /build/rpi3/tmp/portage/logs/sys-kernel:upstream-kernel-mainline-5.4.21-r2:20200901-151628.log
 * Stable log symlink: /build/rpi3/tmp/portage/sys-kernel/upstream-kernel-mainline-5.4.21-r2/temp/build.log
 * CWD: /var/cache/chromeos-cache/distfiles/target/egit-src/linux
 * S:   /build/rpi3/tmp/portage/sys-kernel/upstream-kernel-mainline-5.4.21-r2/work/upstream-kernel-mainline-5.4.21
20:47:22: ERROR   : Tue Sep  1 20:47:22 IST 2020
20:47:22: ERROR   :  PGID  PPID   PID     ELAPSED     TIME %CPU COMMAND
ERROR   :     8     4     8       38:38 00:00:00  0.0 -bash
ERROR   : 12031     8 12031       25:54 00:00:00  0.0  \_ /bin/bash ./build_packages --board=rpi3 --nowithautotest
ERROR   : 12031 12031 16608       00:00 00:00:00  0.0      \_ /bin/bash ./build_packages --board=rpi3 --nowithautotest
ERROR   : 12031 16608 16609       00:00 00:00:00  0.0          \_ ps f -o pgid,ppid,pid,etime,cputime,%cpu,command
20:47:22: ERROR   : Arguments of 12031: ./build_packages '--board=rpi3' '--nowithautotest'
20:47:22: ERROR   : Backtrace:  (most recent call is last)
20:47:22: ERROR   :  build_packages:376:main(), called: die_err_trap  
20:47:22: ERROR   : 
20:47:22: ERROR   : Command failed:
20:47:22: ERROR   :   Command '( if [[ "${FLAGS_run_goma}" -eq "${FLAGS_TRUE}" ]]; then
ERROR   :     info "Starting goma compiler_proxy."; goma_ctl="${GOMA_DIR:-${HOME}/goma}/goma_ctl.py"; EPYTHON="python2" "${goma_ctl}" restart; trap "EPYTHON=python2 '${goma_ctl}' stop" EXIT;
ERROR   : fi; sudo -E "${EMERGE_CMD[@]}" "${EMERGE_FLAGS[@]}" "${PACKAGES[@]}" )' exited with nonzero code: 1

Thanks
Vikas

**Comment by yunshansimon** [comment]
The latest commit is for branch m83, but your overlays are based on "CHROME_BRANCH=80", please update your cros environment to m83.
