### ISSUE TITLE
build error: failing for gclient sync command

### ISSUE THREAD

**Issue by sujaydesawale** [FydeOS/chromium_os-raspberry_pi#93]
Hi,

I am using r 83 branch for RPi build. I am getting the error for gclient sync command which is attached in the .txt file.
Please have a look at the screenshot.

Regards,
Sujay
[r83_branch_gclient_sync_issue.txt](https://github.com/FydeOS/chromium_os-raspberry_pi/files/5186525/r83_branch_gclient_sync_issue.txt)
![gclient_sync_error](https://user-images.githubusercontent.com/17096599/92442334-52534500-f1cd-11ea-9411-8558d7f759f8.png)

**Comment by yunshansimon** [comment]
update your deploy tools and try again.

**Comment by sujaydesawale** [comment]
Hi Yunshansimon,

Could you please tell me how to update deploy tool? 

Regards,
Sujay

**Comment by yunshansimon** [comment]
Hi, Sujay,
  Pls, ref to install/update deploy tools
<http://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up>
Regards,
Yang.
