### ISSUE TITLE
Facing mesa build error while building packages for rpi3

### ISSUE THREAD

**Issue by durgaphadatare** [FydeOS/chromium_os-raspberry_pi#94]
Hi team,

I am building code for rpi3 with overlay branch r83.
Facing following error while building code for rpi3 in command "./build_packages --board=rpi3 --nowithautotest".

 * ERROR: media-libs/mesa-9999::baseboard-rpi3 failed (depend phase):
 *   EAPI=7 is not supported
 * 
 * Call stack:
 *               ebuild.sh, line 616:  Called source '/mnt/host/source/src/overlays/baseboard-rpi3/media-libs/mesa/mesa-9999.ebuild'
 *        mesa-9999.ebuild, line  16:  Called inherit 'base' 'multilib' 'flag-o-matic' 'meson' 'toolchain-funcs' 'git-2' 'cros-workon'
 *               ebuild.sh, line 317:  Called __qa_source '/mnt/host/source/src/third_party/portage-stable/eclass/meson.eclass'
 *               ebuild.sh, line 112:  Called source '/mnt/host/source/src/third_party/portage-stable/eclass/meson.eclass'
 *            meson.eclass, line  39:  Called die
 * The specific snippet of code:
 *   	*) die "EAPI=${EAPI} is not supported" ;;
 * 
 * CWD: /usr/lib64/python3.6/site-packages
 * S:   /build/rpi3/tmp/portage/media-libs/mesa-9999/work/mesa-9999
Error processing media-libs/mesa-9999, continuing...
12:52:51: ERROR   : Sun Sep  6 12:52:51 IST 2020
12:52:51: ERROR   :  PGID  PPID   PID     ELAPSED     TIME %CPU COMMAND
ERROR   :     8     4     8       03:42 00:00:00  0.0 -bash
ERROR   :  1269     8  1269       01:57 00:00:00  0.0  \_ /bin/bash ./build_packages --board=rpi3 --nowithautotest
ERROR   :  1269  1269  2518       00:00 00:00:00  0.0      \_ /bin/bash ./build_packages --board=rpi3 --nowithautotest
ERROR   :  1269  2518  2519       00:00 00:00:00  0.0          \_ ps f -o pgid,ppid,pid,etime,cputime,%cpu,command
12:52:51: ERROR   : Arguments of 1269: ./build_packages '--board=rpi3' '--nowithautotest'
12:52:51: ERROR   : Backtrace:  (most recent call is last)
12:52:51: ERROR   :  build_packages:265:main(), called: die_err_trap  
12:52:51: ERROR   : 
12:52:51: ERROR   : Command failed:
12:52:51: ERROR   :   Command '"${EMERGE_CMD[@]}" --regen --quiet' exited with nonzero code: 1
12:52:51: ERROR   :   (Note bash sometimes misreports "command not found" as exit code 1 instead of 127)

I have followed following two steps from one of your reply and still getting same error.
 - cros_workon-rpi3 stop mesa
 - emerge-rpi3 mesa

Requesting you to suggest any solution for the same.
Thank you,
Durga

**Comment by yunshansimon** [comment]
Hi, Durga:
There is something wrong with the ebuild of mesa-9999. You can delete this
file safely. Then emerge mesa again.
Regards,
Yang
